import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {CLASSES,createGame,initializeAdventure,heroStats,act,enemyIntent} from '../src/engine.js';
import {createWorld,canStand,worldObjects,activeEnemies,interactWorld,finishWorldDialogue,beginWorldBattle,finishWorldBattle,validAdventureSave,migrateAdventureSave,moveWorld} from '../src/world.js';
import {startChapter,chapterFinish,chapterTrigger,chapterObjective,travelWayflame,PUBLIC_LORE} from '../src/chapter.js';
import {addItem,equipItem,unequipSlot} from '../src/inventory.js';
import {availableCompanions} from '../src/companions.js';
const fixture=id=>{const s={version:2,game:initializeAdventure(createGame(id,'Ash')),world:createWorld()};startChapter(s.world,s.game);return s;};
function visit(s,map,x,y){Object.assign(s.world,{map,x,y,conversation:null});if(!s.world.visited.includes(map))s.world.visited.push(map);assert.ok(canStand(s.world,x,y),`${map} ${x},${y} must be accessible`);}
function commit(s){finishWorldDialogue(s.world,'accept',s.game);s.world.flags.gate=true;s.world.flags.ward=true;assert.ok(chapterFinish(s.world,s.game,'resolve','people'));}
function fight(s,id,map,x,y){visit(s,map,x,y);assert.ok(beginWorldBattle(s.world,s.game,id));let turns=0;while(s.game.status==='battle'&&turns++<100){const h=s.game.hero,c=heroStats(h),intent=enemyIntent(s.game);const action=intent.heavy?'guard':h.hp<c.hp*.4&&s.game.potions?'potion':h.mp>=c.cost?'skill':'attack';assert.ok(act(s.game,action,()=>.35).ok);assert.ok(validAdventureSave(s));}assert.equal(s.game.status,'victory',s.game.hero.id+' must beat '+id+' alone');assert.ok(finishWorldBattle(s.world,s.game,'victory'));assert.ok(validAdventureSave(s));}
test('new chapter keeps class identity, selected counterpart NPC, and later recruitment pacing',()=>{for(const cls of CLASSES){const s=fixture(cls.id);assert.ok(validAdventureSave(s));assert.deepEqual(availableCompanions(s.world,s.game),[]);assert.equal(s.game.companions.length,0);s.world.flags.quest=true;s.world.flags.caretaker=true;assert.equal(finishWorldDialogue(s.world,'recruit:knight',s.game),false);if(['knight','paladin','warrior'].includes(cls.id)){const npc=worldObjects({...s.world,map:cls.id==='warrior'?'approach':'courtyard'},s.game).find(o=>o.id==='counterpart-'+cls.id);assert.ok(npc);visit(s,npc.map,npc.x,npc.y+24);const talk=interactWorld(s.world,s.game);assert.match(talk.lines[0],/same calling/);assert.equal(talk.finish,null);}assert.equal(s.game.hero.id,cls.id);}});
test('equipment affects actual strikes, mitigation and focus; ownership and combat restrictions hold',()=>{const a=fixture('knight'),b=fixture('knight');addItem(a.game,'tempered-knight');addItem(a.game,'mended-cloak');addItem(a.game,'veilglass-mirror');assert.ok(equipItem(a.game,'knight','tempered-knight'));assert.ok(equipItem(a.game,'knight','mended-cloak'));assert.ok(equipItem(a.game,'knight','veilglass-mirror'));visit(a,'forest',304,368);visit(b,'forest',304,368);beginWorldBattle(a.world,a.game,'wood-wolf');beginWorldBattle(b.world,b.game,'wood-wolf');a.game.hero.mp=b.game.hero.mp=0;const equipped=act(a.game,'attack',()=>0),bare=act(b.game,'attack',()=>0);assert.equal(equipped.damage-bare.damage,3);assert.equal(bare.enemyDamage-equipped.enemyDamage,2);assert.equal(a.game.hero.mp-b.game.hero.mp,1);assert.equal(unequipSlot(a.game,'knight','armor'),false);assert.equal(equipItem(a.game,'knight','travel-coat'),false);const forged=structuredClone(a);forged.game.hero.equipment.charm='tempered-knight';assert.equal(validAdventureSave(forged),false);});
test('chapter decisions, puzzle prefix, universal tool, and gated physical passage persist',()=>{for(const cls of CLASSES){const s=fixture(cls.id);assert.equal(chapterFinish(s.world,s.game,'resolve','people'),false);commit(s);visit(s,'shrine',480,176);assert.equal(canStand(s.world,480,120),false);assert.equal(chapterFinish(s.world,s.game,'open-seal'),false);chapterFinish(s.world,s.game,'rune-ember');assert.deepEqual(s.world.chapter.puzzle,[]);for(const id of ['root','ward','ember'])chapterFinish(s.world,s.game,'rune-'+id);assert.equal(chapterFinish(s.world,s.game,'open-seal'),false);chapterFinish(s.world,s.game,'take-mirror');assert.ok(s.game.inventory.includes('veilglass-mirror'));const mp=s.game.hero.mp;assert.ok(chapterFinish(s.world,s.game,'open-seal'));assert.equal(s.game.hero.mp,mp);assert.ok(canStand(s.world,480,120));visit(s,'shrine',480,176);for(let i=0;i<25&&s.world.map==='shrine';i++)moveWorld(s.world,0,-1,.05,true);assert.equal(s.world.map,'sanctuary');assert.ok(validAdventureSave(s));const recovered=migrateAdventureSave(s);assert.deepEqual(recovered,s);assert.equal(s.world.chapter.resolve,'people');assert.equal(travelWayflame(s.world,s.game,'forest'),false);}});
test('every starting class can finish Chapter I without companions, grinding, or restoring the central fire',()=>{for(const cls of CLASSES){const s=fixture(cls.id);commit(s);chapterFinish(s.world,s.game,'take-cloak');equipItem(s.game,cls.id,'mended-cloak');fight(s,'wood-wolf','forest',304,368);fight(s,'wood-sentinel','forest',480,192);visit(s,'shrine',480,176);for(const id of ['root','ward','ember'])chapterFinish(s.world,s.game,'rune-'+id);chapterFinish(s.world,s.game,'take-mirror');equipItem(s.game,cls.id,'veilglass-mirror');chapterFinish(s.world,s.game,'open-seal');visit(s,'sanctuary',480,492);const dialogue=chapterTrigger(s.world);assert.equal(dialogue.finish,'confront-ritual');assert.deepEqual(activeEnemies(s.world),[]);chapterFinish(s.world,s.game,dialogue.finish);assert.equal(activeEnemies(s.world).length,1);fight(s,'shrine-warden','sanctuary',480,336);assert.ok(s.game.inventory.includes('ember-glass'));assert.ok(chapterFinish(s.world,s.game,'restore-light'));assert.ok(travelWayflame(s.world,s.game,'courtyard'));assert.ok(chapterFinish(s.world,s.game,'chapter-complete'));assert.equal(chapterObjective(s.world).complete,true);assert.equal(s.game.hero.id,cls.id);assert.equal(s.game.companions.length,0);assert.ok(validAdventureSave(s));assert.match(PUBLIC_LORE.light.text,/not rekindled the First Fire/);assert.deepEqual(migrateAdventureSave(s),s);}});
test('validation rejects contradictory chapter states and malicious choices without altering old saves',()=>{const s=fixture('witch');for(const mutate of [s=>s.world.chapter.completed=true,s=>s.world.chapter.puzzle=['ember'],s=>s.world.chapter.lore.push('engine'),s=>s.world.chapter.sealOpened=true,s=>s.world.chapter.wayflames.push('sanctuary'),s=>s.world.chapter.committed=true]){const bad=structuredClone(s);mutate(bad);assert.equal(validAdventureSave(bad),false);}const old={version:2,game:initializeAdventure(createGame('monk')),world:createWorld()};assert.deepEqual(migrateAdventureSave(old),old);assert.equal(migrateAdventureSave(old).world.chapter,undefined);});
test('future revelation is absent from early runtime modules and public lore',()=>{for(const file of ['src/chapter.js','src/pause-view.js','src/world.js','src/app.js']){assert.doesNotMatch(readFileSync(new URL('../'+file,import.meta.url),'utf8'),/Cinder Engine|First Keepers|stolen vitality|world[’']s imprisonment/i);}assert.doesNotMatch(JSON.stringify(PUBLIC_LORE),/extraction|constructed the fire|created the First Fire/i);});

test('early exploration cannot obscure the required resolve and story phases follow map transitions',()=>{const s=fixture('knight');finishWorldDialogue(s.world,'accept',s.game);s.world.flags.gate=true;s.world.flags.ward=true;visit(s,'shrine',480,560);assert.equal(chapterObjective(s.world).title,'Return with what you know');assert.equal(chapterFinish(s.world,s.game,'open-seal'),false);commit(s);visit(s,'forest',480,42);moveWorld(s.world,0,-1,.05,true);assert.equal(s.world.map,'shrine');assert.equal(s.world.chapter.phase,'ruins');assert.ok(validAdventureSave(s));});
