import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {spawn} from 'node:child_process';
import {existsSync} from 'node:fs';
import {readFile} from 'node:fs/promises';
import {heroStats,enemyIntent} from '../src/engine.js';
import {WORLD_SAVE_KEY,validAdventureSave} from '../src/world.js';
const base='http://127.0.0.1:3109',key=WORLD_SAVE_KEY,errors=[];
const server=spawn(process.execPath,['server.mjs'],{cwd:new URL('../',import.meta.url),env:{...process.env,PORT:'3109'},stdio:['ignore','pipe','pipe']});let browser;
try{
 await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);server.once('exit',code=>reject(new Error(`Server exited ${code}`)));});
 browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||['/usr/bin/chromium','/usr/bin/chromium-browser'].find(existsSync),headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:1100},reducedMotion:'reduce'});page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});await page.addInitScript(()=>{Math.random=()=>.35;window.testAudioStarts=0;window.testAudioContexts=[];const Native=window.AudioContext;window.AudioContext=class extends Native{constructor(...args){super(...args);window.testAudioContexts.push(this);}createOscillator(){const node=super.createOscillator(),start=node.start.bind(node);node.start=(...args)=>{window.testAudioStarts++;return start(...args);};return node;}};});
 const saved=()=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)),key);
 async function ready(){await page.locator('.world-loading').waitFor({state:'hidden'});}
 // Relocate only the explorer to speed repeated browser coverage. All flags,
 // puzzles, inventory, dialogue decisions and combat rewards are earned in UI.
 async function place(map,x,y){const s=await saved();Object.assign(s.world,{map,x,y,conversation:null,grace:64});if(!s.world.visited.includes(map))s.world.visited.push(map);assert.ok(validAdventureSave(s),`valid placement ${map} ${x},${y}`);await page.evaluate(({key,s})=>localStorage.setItem(key,JSON.stringify(s)),{key,s});await page.reload();await ready();}
 async function talk(){await page.locator('#world-canvas').focus();await page.keyboard.press('e');await page.locator('.explore-dialogue').waitFor();}
 async function finishTalk(choice){while(await page.locator('[data-talk-next]').count())await page.locator('[data-talk-next]').click();if(choice)await page.locator(`[data-talk-choice="${choice}"]`).click();}
 async function menu(tab){if(!(await page.locator('dialog[open]').count())){await page.locator('#world-canvas').focus();await page.keyboard.press('p');}await page.locator(`[data-action="menu-tab"][data-tab="${tab}"]`).click();}
 async function fight(){await page.locator('.party-arena').waitFor();if(await page.locator('dialog[open]').count())await page.locator('dialog [data-action="close"]').last().click();let moves=0,s=await saved();while(s.game.status==='battle'&&moves++<100){const stats=heroStats(s.game.hero),intent=enemyIntent(s.game);const action=intent.heavy?'guard':s.game.hero.hp<stats.hp*.4&&s.game.potions?'potion':s.game.hero.mp>=stats.cost?'skill':'attack';await page.locator(`.command[data-action="${action}"]`).click();await page.locator('.arena[data-resolving="false"]').waitFor();s=await saved();assert.ok(validAdventureSave(s));}assert.equal(s.game.status,'victory');await page.locator('[data-action="battle-finish"]').click();await ready();}
 await page.goto(base);assert.match(await page.locator('.cinematic h1').innerText(),/light we were given/);await page.locator('[data-action="cinematic-next"]').click();await page.reload();assert.equal((await saved()).game.cinematicPage,1);for(let i=0;i<3;i++)await page.locator('[data-action="cinematic-next"]').click();await page.locator('#wanderer-name').fill('Ash');await page.locator('#name-form button').click();await page.locator('[data-class="knight"]').click();assert.match(await page.locator('.calling-preview>p').innerText(),/people behind them/);await page.locator('[data-action="accept-class"]').click();await ready();assert.ok((await saved()).world.chapter);assert.ok(validAdventureSave(await saved()));
 await place('courtyard',656,376);await talk();assert.match(await page.locator('.explore-dialogue p').innerText(),/same calling/);await finishTalk();assert.equal((await saved()).game.companions.length,0);
 await place('courtyard',176,256);await talk();await finishTalk();assert.equal((await saved()).world.map,'home');await ready();await page.screenshot({path:'/tmp/hollow-home.png',fullPage:true});
 await place('home',256,456);await talk();await finishTalk();assert.ok((await saved()).game.inventory.includes('mended-cloak'));await menu('equipment');await page.locator('[data-action="equip"][data-item="mended-cloak"]').click();assert.equal((await saved()).game.hero.equipment.armor,'mended-cloak');await page.keyboard.press('Escape');
 await place('home',480,594);await page.locator('#world-canvas').focus();await page.keyboard.down('ArrowDown');await page.waitForFunction(()=>document.querySelector('#world-canvas').dataset.map==='courtyard');await page.keyboard.up('ArrowDown');assert.ok(validAdventureSave(await saved()));
 for(const [id,x,y] of [['oryn',672,288],['baker',544,456],['tavi',368,512],['skeptic',704,424]]){await place('courtyard',x,y);await talk();await finishTalk();assert.ok((await saved()).world.chapter.spoken.includes(id));}
 await place('courtyard',400,336);await talk();await finishTalk();assert.ok((await saved()).world.flags.quest);
 await place('approach',560,288);await talk();await finishTalk();assert.ok((await saved()).world.flags.gate);await place('approach',848,336);await talk();await finishTalk();assert.ok((await saved()).world.flags.ward);await place('courtyard',400,336);await talk();await finishTalk();assert.equal(await page.locator('[data-talk-choice]').count(),3);await page.reload();assert.equal(await page.locator('[data-talk-choice]').count(),3);await page.locator('[data-talk-choice="try"]').click();assert.equal((await saved()).world.chapter.resolve,'try');
 console.log('PASS: cinematic progress, ordinary backgrounds, counterpart identity, interiors, actual equipment, residents and explicit saved resolve');
 await place('forest',304,368);await page.locator('#world-canvas').focus();await page.keyboard.press('e');await fight();await place('forest',480,192);await page.locator('#world-canvas').focus();await page.keyboard.press('e');await fight();await place('forest',592,440);await talk();await finishTalk();assert.ok((await saved()).world.chapter.camp);
 await place('forest',864,288);await talk();await finishTalk();assert.ok((await saved()).world.chapter.wayflames.includes('forest'));
 await place('shrine',688,400);await talk();assert.match(await page.locator('.explore-dialogue p').innerText(),/ROOT/);await finishTalk();await place('shrine',640,336);await talk();await finishTalk();assert.deepEqual((await saved()).world.chapter.puzzle,[]);
 for(const [id,x,y] of [['root',320,336],['ward',480,384],['ember',640,336]]){await place('shrine',x,y);await talk();await finishTalk();assert.equal((await saved()).world.chapter.puzzle.at(-1),id);await page.reload();await ready();}
 await place('shrine',624,512);await talk();await finishTalk();assert.ok((await saved()).world.chapter.technique);await menu('equipment');await page.locator('[data-action="equip"][data-item="veilglass-mirror"]').click();await page.keyboard.press('Escape');await place('shrine',480,176);await talk();await finishTalk();assert.ok((await saved()).world.chapter.sealOpened);
 // Walk through the unlocked passage, then into the trigger area.
 await page.locator('#world-canvas').focus();await page.keyboard.down('ArrowUp');await page.waitForFunction(()=>document.querySelector('#world-canvas').dataset.map==='sanctuary');await page.keyboard.up('ArrowUp');await page.keyboard.down('ArrowUp');await page.waitForSelector('.explore-dialogue');await page.keyboard.up('ArrowUp');assert.match(await page.locator('.dialogue-heading').innerText(),/ritualist/);await page.locator('[data-talk-next]').click();await page.reload();assert.equal((await saved()).world.conversation.page,1);await finishTalk();assert.ok((await saved()).world.chapter.ritualSeen);await page.screenshot({path:'/tmp/hollow-sanctuary.png',fullPage:true});
 await place('sanctuary',480,336);await page.locator('#world-canvas').focus();await page.keyboard.press('e');await fight();assert.ok((await saved()).world.cleared.includes('shrine-warden'));await place('sanctuary',480,192);await talk();await finishTalk();assert.ok((await saved()).world.chapter.lightRestored);
 console.log('PASS: visible battles and tutorial, camp evidence, persistent puzzle with wrong-order reset, universal relic, physical sealed passage, ritual reload, Warden and local restoration');
 await menu('map');await page.locator('[data-action="way-travel"][data-map="courtyard"]').click();assert.equal((await saved()).world.map,'courtyard');await place('courtyard',400,336);await talk();await finishTalk();await page.locator('[data-action="ending-return"]').waitFor();await page.screenshot({path:'/tmp/hollow-chapter-complete.png',fullPage:true});assert.ok((await saved()).world.chapter.completed);await page.reload();await page.locator('[data-action="ending-return"]').click();assert.ok((await saved()).world.chapter.endingSeen);
 for(const tab of ['party','character','equipment','relics','inventory','abilities','journal','lore','map','system']){await menu(tab);assert.ok((await page.locator('.pause-content').innerText()).length>70);assert.equal(await page.locator('dialog h2').count(),1);}
 await page.locator('[data-action="save-now"]').click();assert.match(await page.locator('#system-status').innerText(),/saved/);const download=page.waitForEvent('download');await page.locator('[data-action="export-save"]').click();assert.equal((await download).suggestedFilename(),'the-hollow-save.json');const snapshot=await saved();await page.locator('#save-import').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"broken":true}')});await page.waitForFunction(()=>document.querySelector('#system-status').textContent.includes('not a valid'));assert.deepEqual(await saved(),snapshot);await page.locator('#save-import').setInputFiles({name:'journey.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(snapshot))});await ready();assert.deepEqual(await saved(),snapshot);await menu('system');await page.locator('[data-action="load-now"]').click();await ready();assert.deepEqual(await saved(),snapshot);await menu('system');await page.locator('[data-action="sound"]').last().click();assert.equal(await page.locator('.header-actions [data-action="sound"]').getAttribute('aria-label'),'Mute sound');assert.ok(await page.evaluate(()=>window.testAudioStarts>=3&&window.testAudioContexts[0].state==='running'));await page.locator('[data-action="sound"]').last().click();assert.equal(await page.evaluate(()=>window.testAudioContexts[0].state),'suspended');await page.keyboard.press('Escape');
 await place('courtyard',816,256);await talk();await finishTalk();await place('supply',624,368);await talk();await finishTalk();const before=(await saved()).game.gold;await page.locator('[data-action="buy"][data-item="tempered-knight"]').click();assert.equal((await saved()).game.gold,before-20);assert.ok((await saved()).game.inventory.includes('tempered-knight'));await page.keyboard.press('Escape');
 for(const width of [390,320]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await menu('equipment');assert.equal(await page.evaluate(()=>document.querySelector('dialog').scrollWidth>document.querySelector('dialog').clientWidth),false);if(width===390)await page.screenshot({path:'/tmp/hollow-chapter-menu-mobile.png',fullPage:true});await page.keyboard.press('Escape');}
 assert.ok(validAdventureSave(await saved()));await page.reload();await ready();assert.ok((await saved()).world.chapter.completed);assert.equal((await saved()).game.hero.equipment.armor,'mended-cloak');assert.ok((await saved()).world.chapter.lore.includes('light'));
 const html=await readFile(new URL('../play.html',import.meta.url),'utf8');assert.doesNotMatch(html,/Cinder Engine|First Keepers|stolen vitality|world[’']s imprisonment/i);assert.deepEqual(errors,[]);
 console.log('PASS: saved completion, changed settlement, Wayflame travel, all 10 management tabs, shop, save export, audio toggle, mobile menu, and spoiler-free standalone bundle');
}finally{await browser?.close();server.kill();}
