import assert from 'node:assert/strict';
import {test} from 'node:test';
import {readFileSync} from 'node:fs';
import {CLASSES,createGame,initializeAdventure,act,actor,heroStats,enemyIntent} from '../src/engine.js';
import {createWorld,canStand,mapExits,validAdventureSave,migrateAdventureSave,beginWorldBattle,finishWorldBattle,enemySpawns,moveWorld,finishWorldDialogue} from '../src/world.js';
import {startChapter,chapterFinish,travelWayflame,chapterObjective} from '../src/chapter.js';
import {startSecond,secondFinish,secondObjects,SECOND_CHOICES,SECOND_MAPS,SECOND_LORE} from '../src/chapter-two.js';
import {guideDestination,guidePath,questTarget} from '../src/guidance.js';
import {equipItem,addItem} from '../src/inventory.js';
function completed(id='witch'){
 const game=initializeAdventure(createGame(id,'Ash')),world=startChapter(createWorld(),game);Object.assign(world.flags,{caretaker:true,quest:true,gate:true,ward:true,reported:true,shrine:true});Object.assign(world.chapter,{committed:true,resolve:'people',puzzle:['root','ward','ember'],puzzleSolved:true,technique:true,sealOpened:true,ritualStarted:true,ritualSeen:true,lightRestored:true,completed:true,endingSeen:true,wayflames:['courtyard','sanctuary']});world.cleared=['shrine-warden'];addItem(game,'veilglass-mirror');assert.ok(validAdventureSave({version:2,game,world}));return {version:2,game,world};
}
function visit(s,map,x=480,y=336){Object.assign(s.world,{map,x,y,conversation:null});if(!s.world.visited.includes(map))s.world.visited.push(map);}
function recruit(s,id){if(s.game.hero.id===id)return;const o=secondObjects(s.world,s.game).find(o=>o.classId===id);Object.assign(s.world,{x:o.x,y:o.y+32});assert.ok(secondFinish(s.world,s.game,'second-recruit-'+id));}
function ready(s,choice){assert.ok(startSecond(s.world,s.game));assert.ok(secondFinish(s.world,s.game,'second-request'));for(const id of ['knight','paladin'])recruit(s,id);visit(s,'greyfen',480,400);assert.ok(secondFinish(s.world,s.game,'second-brace'));visit(s,'hollows');assert.ok(secondFinish(s.world,s.game,'second-record'));assert.ok(secondFinish(s.world,s.game,'second-kindle'));visit(s,'lornwatch');assert.ok(secondFinish(s.world,s.game,'second-choice',choice));if(choice==='channels'){visit(s,'hollows',480,448);assert.ok(secondFinish(s.world,s.game,'second-channels'));}}
test('each of seven starting classes completes each beacon decision without duplicate companions or grinding',()=>{for(const cls of CLASSES)for(const choice of SECOND_CHOICES){const s=completed(cls.id);ready(s,choice.value);assert.equal(s.game.companions.length,['knight','paladin'].includes(cls.id)?1:2);assert.ok(!s.game.companions.some(h=>h.id===cls.id));assert.equal(new Set([s.game.hero.id,...s.game.companions.map(h=>h.id)]).size,s.game.companions.length+1);
 addItem(s.game,'mended-cloak');equipItem(s.game,cls.id,'mended-cloak');visit(s,'beacon',480,352);assert.ok(beginWorldBattle(s.world,s.game,'thorn-sentinel'));let steps=0;
 while(s.game.status==='battle'&&steps++<200){const h=actor(s.game),stats=heroStats(h),intent=enemyIntent(s.game),action=intent.heavy?'guard':h.hp<stats.hp*.35&&s.game.potions?'potion':h.mp>=stats.cost?'skill':'attack';assert.ok(act(s.game,action,()=>0).ok);assert.ok(validAdventureSave(s),cls.id+' '+choice.value+' save during combat');}
 assert.equal(s.game.status,'victory',cls.id+' '+choice.value);assert.ok(finishWorldBattle(s.world,s.game,'victory'));assert.ok(secondFinish(s.world,s.game,'second-light'));visit(s,'lornwatch');assert.ok(secondFinish(s.world,s.game,'second-complete'));assert.equal(secondFinish(s.world,s.game,'second-complete'),false);assert.ok(s.game.inventory.includes('thorn-signet'));assert.equal(chapterObjective(s.world).complete,true);assert.ok(validAdventureSave(s));assert.deepEqual(migrateAdventureSave(s),s);assert.equal(s.world.chapter.completed,true);assert.equal(s.game.hero.id,cls.id);
}});
test('Chapter II gates and reserves use explicit state, all roads and objectives have safe routes',()=>{const s=completed();assert.ok(startSecond(s.world,s.game));assert.equal(canStand({...s.world,map:'greyfen'},480,472),false);assert.equal(secondFinish(s.world,s.game,'second-choice','shelter'),false);assert.equal(secondFinish(s.world,s.game,'second-record'),false);assert.equal(secondFinish(s.world,s.game,'second-light'),false);assert.equal(secondFinish(s.world,s.game,'second-complete'),false);secondFinish(s.world,s.game,'second-request');recruit(s,'knight');recruit(s,'paladin');s.game.activeIds=[s.game.hero.id];visit(s,'greyfen',480,400);assert.ok(secondFinish(s.world,s.game,'second-brace'),'reserve exploration works');assert.equal(canStand(s.world,480,472),true);visit(s,'hollows');secondFinish(s.world,s.game,'second-record');secondFinish(s.world,s.game,'second-kindle');visit(s,'lornwatch');secondFinish(s.world,s.game,'second-choice','channels');assert.equal(canStand({...s.world,map:'beacon'},480,224),false);visit(s,'hollows');secondFinish(s.world,s.game,'second-channels');assert.equal(canStand({...s.world,map:'beacon'},480,224),true);
 for(const map of Object.keys(SECOND_MAPS)){visit(s,map,480,map==='beacon'?560:map==='hollows'?192:336);for(const o of secondObjects(s.world,s.game)){const path=guidePath(s.world,s.game,{...o,map});assert.ok(path.length,map+': '+o.id+' reachable');for(const p of path)assert.ok(canStand(s.world,p.x,p.y,s.game));}for(const exit of mapExits(s.world)){const dest={...exit,kind:'exit',x:exit.edge==='west'?28:exit.edge==='east'?932:480,y:exit.edge==='north'?36:exit.edge==='south'?604:336};assert.ok(guidePath(s.world,s.game,dest).length,map+' '+exit.edge);}}
});
test('coordinated different abilities break thorn shell; it renews after enemy phase',()=>{const s=completed();ready(s,'shelter');visit(s,'beacon',480,352);beginWorldBattle(s.world,s.game,'thorn-sentinel');assert.equal(enemyIntent(s.game).shell,true);const first=act(s.game,'skill',()=>0);assert.equal(first.shellBroken,undefined);assert.equal(s.game.enemy.thornBroken,false);const second=act(s.game,'skill',()=>0);assert.equal(second.shellBroken,true);assert.equal(enemyIntent(s.game).shell,false);act(s.game,'guard',()=>0);assert.equal(s.game.round,2);assert.equal(s.game.enemy.thornBroken,false);assert.deepEqual(s.game.enemy.combo,[]);assert.equal(enemyIntent(s.game).shell,true);});
test('Chapter II dialogue choices, discoveries, optional parcel, Wayflames and consequences persist',()=>{const s=completed();ready(s,'ration');visit(s,'lornwatch');s.world.conversation={id:'second-steward',speaker:'Steward Elna',lines:['A promise'],page:0,lastLabel:'Choose',finish:'second-choice',choices:SECOND_CHOICES};assert.ok(validAdventureSave(s));s.world.conversation=null;assert.equal(secondFinish(s.world,s.game,'second-choice','shelter'),false);secondFinish(s.world,s.game,'second-parcel');visit(s,'greyfen');assert.ok(secondFinish(s.world,s.game,'second-delivery'));const gold=s.game.gold;assert.equal(secondFinish(s.world,s.game,'second-delivery'),false);assert.equal(s.game.gold,gold);secondFinish(s.world,s.game,'second-camp');assert.deepEqual(s.world.chapterTwo.trust,['knight','paladin']);assert.ok(finishWorldDialogue(s.world,'way-greyfen',s.game));assert.ok(travelWayflame(s.world,s.game,'lornwatch'));assert.ok(travelWayflame(s.world,s.game,'courtyard'));assert.ok(validAdventureSave(s));assert.deepEqual(migrateAdventureSave(s),s);
 for(const mutate of [x=>x.world.chapterTwo.restored=true,x=>x.world.chapterTwo.decision='forged',x=>x.world.chapterTwo.completed=true,x=>x.world.chapterTwo.lore.push('secret'),x=>x.world.chapterTwo.channels=true]){const bad=structuredClone(s);mutate(bad);assert.equal(validAdventureSave(bad),false);}
});
test('next region unavailable before Chapter I ending, no early hidden truth in Chapter II content',()=>{const game=initializeAdventure(createGame('knight')),world=startChapter(createWorld(),game);assert.equal(startSecond(world,game),false);assert.ok(!mapExits({...world,map:'forest'}).some(e=>e.destination==='lornwatch'));assert.equal(enemySpawns({...world,map:'greyfen'}).some(e=>e.id==='greyfen-wolf'),false);assert.doesNotMatch(readFileSync(new URL('../src/chapter-two.js',import.meta.url),'utf8'),/Cinder Engine|First Keepers|stolen vitality|world[’']s imprisonment/i);assert.doesNotMatch(JSON.stringify(SECOND_LORE),/extraction|created the First Fire/i);});

test('recruited NPC footprints disappear from save validation and new region props remain solid',()=>{const s=completed();ready(s,'shelter');visit(s,'lornwatch',336,352);assert.equal(canStand(s.world,336,352,s.game),true);assert.ok(validAdventureSave(s),'Standing where recruited Aldren was must not discard a valid journey on reload');assert.deepEqual(migrateAdventureSave(s),s);visit(s,'lornwatch',624,384);assert.ok(validAdventureSave(s),'Ilyra’s vacated place is valid too');visit(s,'greyfen');assert.equal(canStand(s.world,672,336,s.game),false,'Camp hearth is solid');assert.equal(canStand(s.world,304,256,s.game),false,'Wayflame is solid');assert.equal(canStand(s.world,480,432,s.game),true,'Reinforced crossing is walkable ground');});
