import test from 'node:test';
import assert from 'node:assert/strict';
import {CLASSES,createGame,chooseClass,heroStats,actor,startEncounter,act,descend,enemyIntent,validSave} from '../src/engine.js';
const zero=()=>0;
function battle(id='knight'){const s=createGame(id,'Ash');startEncounter(s);return s;}
function strategy(s){const h=s.hero,c=heroStats(h);if(h.hp<c.hp*.42&&s.potions>0)return 'potion';if(enemyIntent(s).heavy&&h.hp<c.hp*.7)return 'guard';if(h.mp>=c.cost)return 'skill';return 'attack';}
test('intro creates no hero; exactly one class is selected and locked',()=>{const s=createGame();assert.equal(s.status,'intro');assert.equal(s.hero,null);assert.equal(startEncounter(s),false);assert.equal(chooseClass(s,'invalid'),false);assert.equal(chooseClass(s,'monk'),true);assert.equal(s.hero.id,'monk');assert.equal(chooseClass(s,'knight'),false);assert.equal(validSave(s),true);assert.throws(()=>createGame('invalid'));});
test('solo hero acts once, then the enemy responds and a new round begins',()=>{const s=battle();const r=act(s,'attack',zero);assert.equal(s.enemy.hp,99);assert.equal(s.hero.hp,133);assert.equal(s.round,2);assert.equal(r.enemyDamage,12);assert.equal(actor(s).id,'knight');});
test('heavy attack is telegraphed every third round',()=>{const s=battle();assert.equal(enemyIntent(s).heavy,false);act(s,'attack',zero);act(s,'attack',zero);assert.equal(s.round,3);assert.equal(enemyIntent(s).heavy,true);const r=act(s,'attack',zero);assert.equal(r.heavy,true);assert.equal(r.enemyDamage,19);});
test('unusable abilities and potions do not spend a turn or change state',()=>{const s=battle();s.hero.mp=0;const before=structuredClone(s);assert.equal(act(s,'skill').ok,false);assert.equal(act(s,'potion').ok,false);assert.equal(act(s,'bogus').ok,false);assert.deepEqual(s,before);});
test('guard restores focus and health, mitigates the next strike, and clears on another move',()=>{const s=battle();s.hero.hp=100;s.hero.mp=0;const r=act(s,'guard',zero);assert.equal(r.healed,8);assert.equal(r.enemyDamage,3);assert.equal(s.hero.hp,105);assert.equal(s.hero.mp,8);assert.equal(s.hero.guard,true);act(s,'attack',zero);assert.equal(s.hero.guard,false);});
test('shield bash weakens exactly the responding enemy strike',()=>{const s=battle();const r=act(s,'skill',zero);assert.equal(r.damage,30);assert.equal(r.enemyDamage,7);assert.equal(s.enemy.weak,false);assert.equal(act(s,'attack',zero).enemyDamage,12);});
test('soulfire damages immediately and burns for two turns',()=>{const s=battle('sorcerer');const r=act(s,'skill',zero);assert.equal(r.damage,36);assert.equal(r.burnDamage,8);assert.equal(s.enemy.hp,76);assert.equal(s.enemy.burn,1);act(s,'guard',zero);assert.equal(s.enemy.hp,68);assert.equal(s.enemy.burn,0);});
test('healer classes deal damage and heal themselves in a solo battle',()=>{for(const id of ['paladin','witch','monk']){const s=battle(id);s.hero.hp=40;const r=act(s,'skill',zero);assert.ok(r.damage>=24);assert.ok(r.healed>=20);assert.equal(s.hero.hp,40+r.healed-r.enemyDamage);}});
test('potions cap healing and consume one inventory item',()=>{const s=battle();s.hero.hp=120;const r=act(s,'potion',zero);assert.equal(r.healed,25);assert.equal(s.potions,2);assert.equal(s.hero.hp,133);});
test('victory prevents further actions and duplicate rewards',()=>{const s=battle();s.enemy.hp=1;const r=act(s,'attack',zero);assert.equal(r.enemyDamage,0);assert.equal(s.status,'victory');assert.equal(s.gold,75);assert.equal(act(s,'attack').ok,false);assert.equal(s.gold,75);});
test('refuges advance the campaign, level up, fully restore, and increase stats',()=>{const s=battle();s.enemy.hp=1;act(s,'attack',zero);s.hero.hp=20;s.hero.mp=0;assert.equal(descend(s),true);const c=heroStats(s.hero);assert.equal(s.depth,1);assert.equal(s.hero.level,2);assert.equal(c.hp,160);assert.equal(c.attack,24);assert.equal(s.hero.hp,c.hp);assert.equal(s.hero.mp,c.mp);assert.equal(s.potions,4);assert.equal(s.enemy.hp,170);assert.equal(validSave(s),true);});
test('defeat ends the run, with no further action permitted',()=>{const s=battle();s.hero.hp=1;act(s,'attack',zero);assert.equal(s.status,'defeat');assert.equal(actor(s),null);assert.equal(act(s,'guard').ok,false);assert.equal(validSave(s),true);});
test('solo saves are validated and legacy party saves are rejected without modifying them',()=>{const s=battle();act(s,'attack',zero);assert.equal(validSave(JSON.parse(JSON.stringify(s))),true);for(const mutate of [s=>s.hero.hp=-1,s=>s.depth=10,s=>s.hero.id='invalid',s=>s.hero.level=8,s=>s.enemy.maxHp=1,s=>s.log=null,s=>s.version=1]){const bad=structuredClone(s);mutate(bad);assert.equal(validSave(bad),false);}assert.equal(validSave(createGame()),true);});
test('all seven classes can finish the solo campaign across ten seeded runs each',()=>{for(const c of CLASSES){for(let seed=1;seed<=10;seed++){let n=seed;const rng=()=>((n=(n*1664525+1013904223)>>>0)/4294967296);const s=battle(c.id);let turns=0;while(s.status!=='complete'&&s.status!=='defeat'&&turns++<200){if(s.status==='victory')descend(s);else assert.equal(act(s,strategy(s),rng).ok,true);assert.equal(validSave(s),true);}assert.equal(s.status,'complete',`${c.id} seed ${seed} should be viable`);assert.equal(s.gold,395);assert.equal(s.hero.level,3);assert.equal(descend(s),false);}}});
