import sharp from 'sharp';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {measureRows,silhouette} from '../src/frame-atlas.js';
import {enemyMove} from '../src/animations.js';
import {createAudioDirector,EFFECTS} from '../src/audio.js';
test('uneven atlas rows use actual transparent gutters instead of cutting adjacent poses',()=>{const width=20,height=60,pixels=new Uint8ClampedArray(width*height*4);for(const [lo,hi] of [[3,19],[25,40],[46,57]])for(let y=lo;y<=hi;y++)for(let x=3;x<=16;x++){pixels[(y*width+x)*4]=128;pixels[(y*width+x)*4+3]=255;}const bounds=measureRows(pixels,width,height,4,3);assert.ok(bounds[1]>19&&bounds[1]<25);assert.ok(bounds[2]>40&&bounds[2]<46);assert.deepEqual([bounds[0],bounds[3]],[0,60]);});
test('frame registration ignores adjacent-row fragments and anchors the main visible foot',()=>{const width=40,height=40,pixels=new Uint8ClampedArray(width*height*4);const paint=(x,y)=>{pixels[(y*width+x)*4]=180;pixels[(y*width+x)*4+3]=255;};for(let y=3;y<=29;y++)for(let x=7;x<=20;x++)paint(x,y);paint(34,38);paint(35,38);const b=silhouette(pixels,width,height);assert.equal(b.area,378);assert.equal(b.bottom,31);assert.ok(b.foot>=7&&b.foot<=20);assert.ok(b.right<34);assert.equal(enemyMove('wolf','death').columns,6);assert.equal(enemyMove('wolf','attack').columns,5);});
test('sound effects share one gesture-enabled context, mute immediately, and clean up voices',async()=>{let contexts=0;const voices=[];class Context{constructor(){contexts++;this.currentTime=0;this.state='suspended';this.destination={};}async resume(){this.state='running';}async suspend(){this.state='suspended';}close(){this.state='closed';}createOscillator(){const voice={frequency:{setValueAtTime:(hz)=>{voice.hz=hz;},exponentialRampToValueAtTime:()=>{}},connect(){},disconnect(){},start(){voice.started=true;},stop(){voice.stopped=true;}};voices.push(voice);return voice;}createGain(){return {gain:{setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){},disconnect(){}};}}
 globalThis.window={AudioContext:Context};const director=createAudioDirector();try{assert.equal(director.effect('hit'),false);assert.equal(contexts,0);assert.equal(await director.setEnabled(true),true);const count=voices.length;for(const name of Object.keys(EFFECTS))assert.equal(director.effect(name),true);assert.ok(voices.length>count);assert.equal(contexts,1);assert.notEqual(EFFECTS.hit.notes[0],EFFECTS.heal.notes[0]);await director.setEnabled(false);const mutedCount=voices.length;assert.equal(director.effect('attack'),false);assert.equal(voices.length,mutedCount);assert.ok(voices.every(v=>v.stopped));await director.setEnabled(true);assert.equal(contexts,1);director.destroy();assert.equal(director.effect('victory'),false);}finally{director.destroy();delete globalThis.window;}});

test('Paladin hammer impact retains a full body for both genders',async()=>{const {data,info}=await sharp(new URL('../public/assets/battle/paladin.png',import.meta.url).pathname).raw().toBuffer({resolveWithObject:true}),rows=measureRows(data,info.width,info.height,4,8);const height=(row,frame)=>{const left=Math.round(frame*info.width/6),right=Math.round((frame+1)*info.width/6),width=right-left,h=rows[row+1]-rows[row],p=new Uint8ClampedArray(width*h*4);for(let y=0;y<h;y++)p.set(data.subarray(((rows[row]+y)*info.width+left)*4,((rows[row]+y)*info.width+right)*4),y*width*4);const body=silhouette(p,width,h);return body.bottom-body.top;};for(const offset of [0,4])assert.ok(height(offset+1,3)>=height(offset,0)*.75,'Impact includes the armored body rather than only the floating hammer');});
