import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {spawn} from 'node:child_process';
import {existsSync} from 'node:fs';
import {readFile} from 'node:fs/promises';
import {CLASSES,createGame,initializeAdventure,actor,enemyIntent} from '../src/engine.js';
import {COMPANIONS,partyMembers} from '../src/companions.js';
import {createWorld,enemySpawns,WORLD_SAVE_KEY,LEGACY_WORLD_SAVE_KEY,validAdventureSave,beginWorldBattle} from '../src/world.js';
const base='http://127.0.0.1:3107',key=WORLD_SAVE_KEY,errors=[];
const server=spawn(process.execPath,['server.mjs'],{cwd:new URL('../',import.meta.url),env:{...process.env,PORT:'3107'},stdio:['ignore','pipe','pipe']});let browser;
const fixture=id=>({version:2,game:initializeAdventure(createGame(id,'Ash')),world:createWorld()});
function unlock(s){Object.assign(s.world.flags,{caretaker:true,quest:true,gate:true,ward:true,reported:true,forestChest:true});s.world.cleared=['wood-sentinel'];}
try{
 await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);server.once('exit',code=>reject(new Error(`Server exited ${code}`)));});
 browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||['/usr/bin/chromium','/usr/bin/chromium-browser'].find(existsSync),headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:1100}});page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});await page.addInitScript(()=>{Math.random=()=>0;});await page.goto(base);
 const saved=()=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)),key);
 // Pause and flush the live world before injecting a fixture; patrol autosave also runs on pagehide.
 async function load(s){assert.ok(validAdventureSave(s),'Browser fixture must pass production save validation');if(await page.locator('#world-canvas').count()&&!(await page.locator('dialog[open]').count()))await page.locator('header [data-action="menu"]').click();await page.evaluate(({key,s})=>localStorage.setItem(key,JSON.stringify(s)),{key,s});await page.goto(base);if(s.game.status==='preparing')await page.locator('.world-loading').waitFor({state:'hidden'});}
 async function finishTalk(){while(await page.locator('[data-talk-next]').count())await page.locator('[data-talk-next]').click();}
 async function command(action){await page.locator(`.command[data-action="${action}"]`).click();await page.locator('.arena[data-resolving="false"]').waitFor();}
 for(const c of CLASSES){await load(fixture(c.id));await page.locator('#world-canvas').focus();
  const poses=await page.evaluate(async id=>{const image=new Image();image.src=`/public/assets/overworld/${id}.png`;await image.decode();const canvas=document.createElement('canvas');canvas.width=64;canvas.height=64;const ctx=canvas.getContext('2d');const rows=[];for(let row=0;row<8;row++){const hashes=[];for(let frame=0;frame<4;frame++){ctx.clearRect(0,0,64,64);ctx.drawImage(image,frame*image.width/4,row*image.height/8,image.width/4,image.height/8,0,0,64,64);const bytes=ctx.getImageData(0,0,64,64).data;let hash=2166136261,alpha=0;for(let i=0;i<bytes.length;i++){hash=Math.imul(hash^bytes[i],16777619);if(i%4===3)alpha+=bytes[i];}hashes.push([hash,alpha]);}rows.push(hashes);}return rows;},c.id);
  assert.ok(poses.every(row=>new Set(row.map(([hash])=>hash)).size===4&&row.every(([,alpha])=>alpha>1000)),`${c.id} needs 32 populated, distinct locomotion poses`);
  for(const [button,walkRow] of [['ArrowDown',0],['ArrowLeft',1],['ArrowUp',2],['ArrowRight',3]]){
   await page.keyboard.down(button);await page.waitForFunction(row=>{const c=document.querySelector('#world-canvas');return c.dataset.motion==='walk'&&Number(c.dataset.animRow)===row&&Number(c.dataset.animFrame)>0;},walkRow);await page.keyboard.down('Shift');await page.waitForFunction(row=>{const c=document.querySelector('#world-canvas');return c.dataset.motion==='run'&&Number(c.dataset.animRow)===row+4;},walkRow);await page.keyboard.up('Shift');await page.keyboard.up(button);
  }
  await page.waitForFunction(()=>document.querySelector('#world-canvas').dataset.motion==='idle');console.log(`PASS: ${c.name} 32 distinct poses and actual four-direction walking/running`);
 }
 const s=fixture('knight');unlock(s);await load(s);
 for(const c of COMPANIONS.filter(c=>c.id!=='knight')){
  const next=await saved();Object.assign(next.world,{map:c.map,x:c.x,y:c.y+24,conversation:null});if(!next.world.visited.includes(c.map))next.world.visited.push(c.map);await load(next);await page.locator('#world-canvas').focus();await page.keyboard.press('e');assert.equal((await saved()).game.companions.some(h=>h.id===c.id),false);await page.locator('[data-talk-next]').click();await page.reload();assert.equal((await saved()).world.conversation.page,1);await finishTalk();assert.ok((await saved()).game.companions.some(h=>h.id===c.id));
 }
 assert.equal(partyMembers((await saved()).game).length,7);await page.locator('.overworld-party [data-action="party"]').click();assert.equal(await page.locator('.companion-card').count(),7);assert.equal(await page.locator('[data-companion="knight"] button').isDisabled(),true);await page.locator('[data-companion="warrior"] button').click();await page.locator('[data-companion="monk"] button').click();assert.deepEqual((await saved()).game.activeIds,['knight','paladin','sorcerer','monk']);await page.locator('dialog .primary-button[data-action="close"]').click();
 console.log('PASS: all six unique recruitment scenes, mid-scene reload, four-person cap, reserves, and locked protagonist');
 const road=await saved(),wolf=enemySpawns(road.world).find(e=>e.id==='wood-wolf');Object.assign(road.world,{map:'forest',x:wolf.x-56,y:wolf.y,conversation:null,grace:0});await load(road);await page.locator('[data-run-toggle]').click();await page.keyboard.down('ArrowRight');await page.locator('.entering-battle').waitFor();await page.keyboard.up('ArrowRight');await page.locator('.party-arena').waitFor();assert.equal(await page.locator('.stage-hero').count(),4);assert.ok(validAdventureSave(await saved()));
 await command('guard');assert.equal(actor((await saved()).game).id,'paladin');assert.equal((await saved()).game.round,1);assert.equal(await page.locator('[data-hero="knight"] .frame-sprite').getAttribute('data-row'),'2');await page.reload();assert.equal(actor((await saved()).game).id,'paladin');await command('skill');await command('skill');assert.equal((await saved()).game.round,1);assert.equal(await page.locator('[data-hero="knight"] .frame-sprite').getAttribute('data-row'),'2');
 await page.locator('.command[data-action="skill"]').click();await page.locator('.arena[data-phase="enemy"]').waitFor();assert.equal(await page.locator('.taking-hit').getAttribute('data-hero'),'knight');assert.equal(await page.locator('[data-hero="knight"] .frame-sprite').getAttribute('data-row'),'2');await page.locator('.arena[data-resolving="false"]').waitFor();assert.equal((await saved()).game.round,2);
 await page.screenshot({path:'/tmp/hollow-party-battle.png',fullPage:true});console.log('PASS: real contact transition, companion commands, saved partial round, held guard and animated enemy target');
 await page.emulateMedia({reducedMotion:'reduce'});let moves=0,current=await saved();while(current.game.status==='battle'&&moves++<30){const h=actor(current.game);await command(h.mp>=CLASSES.find(c=>c.id===h.id).cost?'skill':'attack');current=await saved();}assert.equal(current.game.status,'victory');await page.reload();await page.locator('[data-action="battle-finish"]').click();assert.equal((await saved()).world.cleared.includes('wood-wolf'),true);assert.ok((await saved()).game.companions.every(h=>h.level===2));await page.reload();assert.ok(validAdventureSave(await saved()));
 const field=await saved();Object.assign(field.world,{map:'approach',x:736,y:288,conversation:null});await load(field);await page.locator('#world-canvas').focus();await page.keyboard.press('e');assert.match(await page.locator('.explore-dialogue p').innerText(),/chain/);await finishTalk();assert.ok((await saved()).world.flags['field-gunslinger']);assert.equal((await saved()).game.activeIds.includes('gunslinger'),false);
 console.log('PASS: victory/rewards/levels, persistent cleared encounter, and reserve Gunslinger exploration ability');
 const boss=await saved(),warden=enemySpawns(boss.world).find(e=>e.id==='shrine-warden');Object.assign(boss.world,{map:'shrine',x:warden.x,y:warden.y+32,conversation:null});assert.ok(beginWorldBattle(boss.world,boss.game,'shrine-warden'));boss.game.round=3;await load(boss);assert.match(await page.locator('.intent-description').innerText(),/every living ally/);for(let i=0;i<4;i++)await command('guard');assert.equal((await saved()).game.round,4);assert.match(await page.locator('.intent-description').innerText(),/carapace/);
 for(const width of [390,320]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator('[data-action="party"]').click();assert.equal(await page.locator('[data-companion="monk"] button').isDisabled(),true);await page.keyboard.press('Escape');if(width===390)await page.screenshot({path:'/tmp/hollow-party-mobile.png',fullPage:true});}
 await page.keyboard.press('r');assert.equal((await saved()).game.status,'preparing');assert.ok(!(await saved()).world.cleared.includes('shrine-warden'));await page.setViewportSize({width:1440,height:1100});await page.screenshot({path:'/tmp/hollow-shrine-party.png',fullPage:true});console.log('PASS: boss party-wide guard, stone carapace, mobile combat/menu layouts, and retreat');
 const lost=await saved(),remaining=enemySpawns(lost.world).find(e=>e.id==='shrine-warden');lost.world.x=remaining.x;lost.world.y=remaining.y+32;lost.world.grace=0;assert.ok(beginWorldBattle(lost.world,lost.game,'shrine-warden'));for(const h of partyMembers(lost.game))if(lost.game.activeIds.includes(h.id))h.hp=1;lost.game.round=3;await load(lost);for(let i=0;i<4;i++)await command('attack');assert.equal((await saved()).game.status,'defeat');await page.locator('[data-action="battle-finish"]').click();assert.equal((await saved()).world.map,'courtyard');assert.ok(partyMembers((await saved()).game).every(h=>h.hp>1));console.log('PASS: whole-party defeat recovers at courtyard without removing the guardian');
 const legacy={version:1,game:createGame('witch','Returning'),world:createWorld()};legacy.world.flags.quest=true;legacy.world.flags.caretaker=true;await page.evaluate(({key,legacy,legacyKey})=>{localStorage.removeItem(key);localStorage.setItem(legacyKey,JSON.stringify(legacy));},{key,legacy,legacyKey:LEGACY_WORLD_SAVE_KEY});await page.reload();assert.equal((await saved()).game.name,'Returning');assert.ok((await saved()).world.flags.quest);assert.deepEqual(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)),LEGACY_WORLD_SAVE_KEY),legacy);
 const legacySnapshot=await saved();await page.locator('#world-canvas').focus();await page.keyboard.press('p');await page.locator('[data-action="menu-tab"][data-tab="system"]').click();const backupPromise=page.waitForEvent('download');await page.locator('[data-action="export-save"]').click();await (await backupPromise).saveAs('/tmp/hollow-legacy-backup.json');assert.deepEqual(JSON.parse(await readFile('/tmp/hollow-legacy-backup.json','utf8')),legacySnapshot);assert.deepEqual(await saved(),legacySnapshot);await page.keyboard.press('Escape');console.log('PASS: returning adventure can export an exact backup without altering its party or story');
 const offline=await browser.newPage({reducedMotion:'reduce'}),requests=[];offline.on('pageerror',e=>errors.push(e.message));offline.on('request',r=>{if(r.resourceType()!=='document'&&/^https?:/.test(r.url()))requests.push(r.url());});await offline.goto(`${base}/play.html`);await offline.evaluate(({key,s})=>localStorage.setItem(key,JSON.stringify(s)),{key,s:boss});await offline.reload();await offline.locator('.party-arena').waitFor();await offline.locator('.command[data-action="skill"]').click();await offline.locator('.arena[data-resolving="false"]').waitFor();assert.deepEqual(requests,[]);assert.deepEqual(errors,[]);console.log('PASS: legacy adventure migration and embedded offline party battle without browser errors or external requests');
}finally{await browser?.close();server.kill();}
