import test from 'node:test';
import assert from 'node:assert/strict';
import { createGame, initializeAdventure, heroStats, validSave } from '../src/engine.js';
import { createWorld, canStand, interactWorld, finishWorldDialogue, validAdventureSave, migrateAdventureSave } from '../src/world.js';
import { startChapter } from '../src/chapter.js';
import { ROADHOUSES, purchase, upgradeGear, restAtInn, shopOffers } from '../src/services.js';
import { ITEMS, equipItem, addItem } from '../src/inventory.js';
import { ABILITY_PRESENTATIONS, abilityMove } from '../src/ability-presentation.js';
import { SKILLS } from '../src/skills.js';
import { EFFECTS, musicForScene, createAudioDirector } from '../src/audio.js';
function journey(){const game=initializeAdventure(createGame('knight','Ash')),world=startChapter(createWorld(),game);game.gold=200;return {version:2,game,world};}
test('roadhouses have reachable interaction ground and real inn/shop/forge dialogue',()=>{for(const house of ROADHOUSES){const {game,world}=journey();world.map=house.map;world.visited.push(house.map);const points=[];for(let y=-48;y<=48;y+=8)for(let x=-48;x<=48;x+=8)if(Math.hypot(x,y)<=58&&canStand(world,house.x+x,house.y+y,game))points.push({x:house.x+x,y:house.y+y});const point=points.find(p=>{Object.assign(world,p);return interactWorld(world,game)?.id===house.id;});assert.ok(point,`${house.id} is reachable without entering a wall or overlapping another interaction`);Object.assign(world,point);const dialogue=interactWorld(world,game);world.conversation={...dialogue,page:0};assert.equal(finishWorldDialogue(world,'services',game),true);assert.equal(dialogue.finish,'services');}});
test('shop transactions validate proximity, ownership, recruited classes and available gold',()=>{const save=journey(),{game,world}=save;world.x=608;world.y=400;assert.ok(purchase(game,world,'tempered-knight'));assert.equal(game.gold,180);assert.equal(purchase(game,world,'tempered-knight'),false);assert.equal(purchase(game,world,'tempered-witch'),false);assert.equal(purchase(game,world,'thorn-signet'),false);const pots=game.potions;assert.ok(purchase(game,world,'potion'));assert.equal(game.potions,pots+1);world.x=464;assert.equal(purchase(game,world,'potion'),false);world.x=608;game.gold=14;assert.equal(purchase(game,world,'potion'),false);assert.equal(game.gold,14);assert.ok(validAdventureSave(save));assert.equal(shopOffers(game).length,4);});
test('both forge tiers change equipped combat stats and remain valid across save import',()=>{const save=journey(),{game,world}=save;world.x=608;world.y=400;purchase(game,world,'tempered-knight');equipItem(game,'knight','tempered-knight');const before=heroStats(game.hero).attack;assert.equal(upgradeGear(game,world,'tempered-knight'),false);game.hero.level=3;game.xp=70;assert.ok(upgradeGear(game,world,'tempered-knight'));assert.equal(game.hero.equipment.weapon,'tempered-knight-forge-1');assert.equal(heroStats(game.hero).attack,before+6+3);assert.equal(purchase(game,world,'tempered-knight'),false);assert.ok(upgradeGear(game,world,'tempered-knight-forge-1'));assert.equal(heroStats(game.hero).attack,before+6+6);assert.equal(upgradeGear(game,world,'tempered-knight-forge-2'),false);assert.ok(validAdventureSave(save));assert.deepEqual(migrateAdventureSave(save),save);const bad=structuredClone(game);bad.hero.equipment.weapon='tempered-witch-forge-2';assert.equal(validSave(bad),false);});
test('forge armor applies defense, inn revives reserves and never grants free potions',()=>{const save=journey(),{game,world}=save;Object.assign(world,{x:608,y:400});game.hero.level=2;game.xp=25;const reserve={id:'witch',level:2,hp:0,mp:0,guard:false};game.companions.push(reserve);addItem(game,'starter-witch');purchase(game,world,'mended-cloak');equipItem(game,'knight','mended-cloak');assert.ok(upgradeGear(game,world,'mended-cloak'));assert.equal(heroStats(game.hero).defense,3);assert.ok(purchase(game,world,'ward-armor-witch'));equipItem(game,'witch','ward-armor-witch');assert.equal(heroStats(reserve).defense,3);game.hero.hp=10;game.hero.mp=0;const gold=game.gold,pots=game.potions;assert.ok(restAtInn(game,world));assert.equal(game.gold,gold-5);assert.equal(game.potions,pots);for(const h of [game.hero,reserve]){assert.equal(h.hp,heroStats(h).hp);assert.equal(h.mp,heroStats(h).mp);}assert.ok(validAdventureSave(save));game.gold=4;assert.equal(restAtInn(game,world),false);});
test('every learned technique has a distinct cue, valid full-body pose sequence and visual motif',()=>{const cues=new Set(),motifs=new Set();assert.equal(Object.keys(ABILITY_PRESENTATIONS).length,28);for(const [id,p] of Object.entries(ABILITY_PRESENTATIONS)){assert.ok(SKILLS[id]);assert.equal(abilityMove(SKILLS[id]).party,Boolean(SKILLS[id].effects.partyHeal||SKILLS[id].effects.partyFocus||SKILLS[id].effects.partyGuard));assert.ok(EFFECTS[id]);assert.ok(p.poses.some(([row])=>row===3));assert.ok(p.poses.every(([row,frame])=>row>=1&&row<=3&&frame>=0&&frame<=5));assert.equal(p.poses.length,6);assert.equal(cues.has(JSON.stringify(EFFECTS[id])),false);cues.add(JSON.stringify(EFFECTS[id]));assert.equal(motifs.has(p.motif),false);motifs.add(p.motif);assert.ok(p.duration>=980&&p.duration<=1280);}});
test('overworld, regular battle and boss scores differ, with no premature lore disclosure',()=>{assert.notDeepEqual(musicForScene('battle'),musicForScene('boss'));assert.notDeepEqual(musicForScene('forest'),musicForScene('courtyard'));assert.notDeepEqual(musicForScene('hollows'),musicForScene('greyfen'));assert.ok(musicForScene('boss').drums);assert.ok(musicForScene('boss').bpm>musicForScene('courtyard').bpm);assert.doesNotMatch(JSON.stringify(EFFECTS),/cinder engine|first keepers/i);});
test('audio resumes safely if the scene changes while gesture activation is pending',async()=>{let resume,contexts=0;class Context{constructor(){contexts++;this.currentTime=0;this.state='suspended';this.destination={};}resume(){return new Promise(resolve=>resume=()=>{this.state='running';resolve();});}async suspend(){this.state='suspended';}close(){}createOscillator(){return {frequency:{setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){},disconnect(){},start(){},stop(){}};}createGain(){return {gain:{setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){},disconnect(){}};}}
globalThis.window={AudioContext:Context};const director=createAudioDirector();try{const activation=director.setEnabled(true);director.setScene('boss');resume();assert.equal(await activation,true);assert.equal(director.track,musicForScene('boss').title);assert.equal(contexts,1);assert.ok(director.effect('shield-impact'));assert.equal(await director.setEnabled(false),false);}finally{director.destroy();delete globalThis.window;}});

test('reforging cannot create duplicate gear from an otherwise valid imported inventory',()=>{const {game,world}=journey();Object.assign(world,{x:608,y:400});game.hero.level=3;game.xp=70;addItem(game,'tempered-knight');addItem(game,'tempered-knight-forge-1');const before=structuredClone(game);assert.equal(upgradeGear(game,world,'tempered-knight'),false);assert.deepEqual(game,before);assert.ok(validSave(game));});

test('older adventures receive roadhouse services without a chapter reset or party loss',()=>{const game=initializeAdventure(createGame('witch','Ash')),world=createWorld();Object.assign(world,{x:608,y:400});game.gold=50;game.hero.hp=10;const dialogue=interactWorld(world,game);assert.equal(dialogue.finish,'services');assert.ok(purchase(game,world,'tempered-witch'));assert.ok(restAtInn(game,world));assert.equal(world.chapter,undefined);assert.equal(game.hero.id,'witch');assert.ok(validAdventureSave({version:2,game,world}));});
