import { heroStats, actor, currentEncounter, enemyIntent, woundedMember } from './engine.js';
import { activeParty, memberName } from './companions.js';
import { MAPS } from './world.js';

export function renderPartyBattle({state,world,motion,busy,icon,esc,sprite,hpBar,moveEffects}){
 const e=currentEncounter(state),party=activeParty(state),current=actor(state),c=heroStats(current||state.hero),intent=enemyIntent(state),playing=state.status==='battle';
 const row={wolf:0,sentinel:50,warden:100}[e.sprite];
 const description=c.id==='paladin'?'Deals holy damage and heals the most wounded ally.':c.id==='monk'?'Deals damage, heals self, and restores 3 focus to every ally.':c.description;
 return `<main class="party-battle-main"><section class="page-heading"><div><div class="eyebrow">CHAPTER I · ${esc(MAPS[world.map].name).toUpperCase()}</div><h1>${e.enemy}<span class="title-dot">.</span></h1><p>${e.boss?'A guardian with a duty it no longer understands. Coordinate your whole party.':'The road gives way to battle. Every living companion gets a command each round.'}</p></div><button class="text-button" data-action="retreat" ${!playing||busy?'disabled':''}>Retreat to the road ${icon('arrow',15)}</button></section>
 <div class="game-layout"><section class="battle-column"><div class="arena party-arena region-${world.map}" data-resolving="${busy}" data-phase="${motion?'hero':'idle'}"><div class="arena-shade"></div><div class="arena-top"><span class="location-label">${icon('map',14)} ${esc(MAPS[world.map].name).toUpperCase()}</span><span class="encounter-label"><i></i>${playing?'IN COMBAT':state.status==='victory'?'THREAT DEFEATED':'PARTY FALLEN'}</span></div>
 <div class="enemy-hud"><div class="enemy-heading"><span class="enemy-icon">${icon('crosshair',17)}</span><div><strong>${e.enemy}</strong><small>${e.boss?'Shrine guardian':'Ward-road threat'}</small></div></div>${hpBar(state.enemy.hp,state.enemy.maxHp,'enemy-meter')}<div class="enemy-numbers"><span>${state.enemy.burn?'BURNING · '+state.enemy.burn+' ROUNDS':intent.shell?'STONE CARAPACE':intent.enraged?'ENRAGED':e.boss?'BOSS':'CREATURE'}</span><span>${state.enemy.hp}<em> / ${state.enemy.maxHp}</em></span></div></div>
 <div class="battle-enemy enemy-${e.sprite} ${state.enemy.hp===0?'fallen':''}" style="--enemy-row:${row}%" role="img" aria-label="${e.enemy} pixel art"></div>
 <div class="stage-party adventure-stage">${party.map(h=>{const m=motion?.heroId===h.id?motion:null,stats=heroStats(h);return `<div class="stage-hero ${!h.hp?'fallen':''} ${current?.id===h.id?'stage-active':''} ${h.guard?'guarding':''} ${m?'performing':''}" data-hero="${h.id}" data-move="${m?.action||'idle'}" style="--move-duration:${m?.duration||600}ms;--fx-color:${m?.color||stats.color}">${sprite(h.id,'battle-sprite')}<span class="hero-shadow"></span><span class="guard-ward" aria-hidden="true">${icon('shield',70)}</span>${m?moveEffects(stats):''}<div class="stage-name">${m?m.label:esc(memberName(state,h))}${h.guard?icon('shield',12):''}</div></div>`;}).join('')}</div>
 ${!playing?`<div class="arena-message"><span>${state.status==='victory'?'THE ROAD OPENS':'A LIGHT STILL WAITS'}</span><h2>${state.status==='victory'?'Catch your breath.':'Return to the fire.'}</h2><button class="primary-button" data-action="battle-finish">${state.status==='victory'?`Return · +${e.xp} XP`:'Recover in courtyard'} ${icon('arrow',15)}</button></div>`:''}
 <div class="arena-bottom"><span>${icon('fire',14)} ROUND ${state.round}</span><span>${playing?`${esc(memberName(state,current))}’s command`:'The journey continues.'}</span><span>PARTY ${party.length} / 4</span></div></div>
 <div class="turn-strip"><span class="eyebrow">NEXT ENEMY MOVE</span><span class="turn-token enemy-token ${intent.heavy?'heavy-intent':''}">${icon(intent.heavy?'fire':'crosshair',15)}${intent.name}</span><span class="intent-description">${e.boss&&intent.heavy?'Hits every living ally. Guard across the party.':intent.description}</span></div>
 <div class="party-section-heading"><h3>Your party <span>${party.length} TRAVELLING · LEVEL ${state.hero.level}</span></h3></div><div class="battle-party-cards">${party.map(h=>{const stats=heroStats(h);return `<article class="hero-card ${current?.id===h.id?'selected':''} ${!h.hp?'dead':''} ${state.acted.includes(h.id)?'has-acted':''}" data-member="${h.id}" style="--class-color:${stats.color}"><div class="hero-details"><div class="hero-card-heading"><h3>${esc(memberName(state,h))}</h3><span>${stats.name.toUpperCase()} · ${!h.hp?'DOWN':state.acted.includes(h.id)?'COMMANDED':current?.id===h.id?'YOUR TURN':stats.role.toUpperCase()}</span></div><div class="stat-row"><span>HP</span><b>${h.hp}<em> / ${stats.hp}</em></b></div>${hpBar(h.hp,stats.hp)}<div class="stat-row focus-stat"><span>FOCUS</span><b>${h.mp}<em> / ${stats.mp}</em></b></div>${hpBar(h.mp,stats.mp,'focus-meter')}</div></article>`;}).join('')}</div></section>
 <aside class="side-column"><section class="quest-card"><div class="eyebrow">${icon(c.icon,14)} ${c.role.toUpperCase()}</div><h2>${c.skill}</h2><p>${description}</p><div class="quest-footer"><span>${e.reward} gold · ${e.xp} XP</span><span>${e.boss?'BOSS':'ENCOUNTER'}</span></div></section><section class="journal"><div class="journal-tabs">Battle log</div><div class="journal-content" aria-live="polite">${state.log.slice(-8).map(l=>`<div class="log-entry ${esc(l.type)}"><p>${esc(l.text)}</p></div>`).join('')}</div><div class="journal-bottom">${icon('people',14)} Allies act before the enemy.</div></section><section class="supplies"><span>PARTY SUPPLIES</span><div><span>${icon('flask',18)}<b>${state.potions}</b><small>Potions</small></span><span>${icon('coin',18)}<b>${state.gold}</b><small>Gold</small></span></div></section></aside></div>
 <section class="command-bar" aria-label="Party combat actions"><div class="command-context"><span class="command-symbol">${icon(c.icon,24)}</span><div><span class="eyebrow">${playing?'COMMAND YOUR PARTY':'ENCOUNTER ENDED'}</span><h3>${playing?`${esc(memberName(state,current))}’s turn`:'Return to your journey'}</h3></div></div><div class="commands">${[['attack','sword','Attack',`${c.attack} base damage`,true],['skill',c.icon,c.skill,`${c.cost} focus`,current&&current.mp>=c.cost],['guard','shield','Guard','75% less damage · recover',true],['potion','flask','Potion','Heal or revive weakest ally',state.potions>0&&woundedMember(state)]].map(([action,i,label,sub,available],n)=>`<button class="command ${action==='attack'?'attack-command':''}" data-action="${action}" ${!playing||busy||!available?'disabled':''}><span class="keycap">${n+1}</span>${icon(i,22)}<span><strong>${label}</strong><small>${sub}</small></span></button>`).join('')}</div></section><footer class="page-footer"><span>Each ally acts once. The enemy responds after the party.</span><span>1–4 commands · R retreat</span></footer></main>`;
}
