import { addItem, initializeInventory } from './inventory.js';
import { heroStats, log } from './engine.js';
import { COMPANIONS, partyMembers } from './companions.js';

export const CHAPTER_TITLE='Glimmer of Hope';
export const BACKGROUNDS={knight:'You learned to keep watch on these walls. Your oath is to the people behind them, not to a promised destiny.',warrior:'Your strength has carried neighbors through colder nights. The world has taken much from you; there are still people worth protecting.',paladin:'You tended wounds and small sanctuary lights. Faith means answering when a neighbor asks for help.',sorcerer:'You studied the old ward inscriptions here. Whatever waits beyond the veil, the people of this courtyard are real.',witch:'The old names once helped gardens grow. You know them because someone took the time to teach you.',gunslinger:'You carried letters between settlements. Each delivery was a promise that someone elsewhere still cared.',monk:'You learned to listen before you struck. Lately, the courtyard’s silence has become harder to bear.'};
export const CINEMATIC=[
 {art:'first-fire',title:'The light we were given',text:'The people of Nhalis have always been taught that the First Fire keeps the world alive. Its warmth reached their homes through the ancient wards.'},
 {art:'forest',title:'The long season of ash',text:'Now the wards fall silent. Fields fail, animals turn strange, and the roads between settlements disappear beneath the cold. No one agrees on why the light is fading.'},
 {art:'courtyard',title:'A place called home',text:'In the Ember Courtyard, tomorrow is measured in firewood, flour, and letters that have not arrived. This is where you live. These are the people you know.'},
 {art:'shrine',title:'While an ember remains',text:'Some pray. Some wait for the end. Beyond the ward road, the Ashen Covenant welcomes it. No prophecy names you. There is only a choice: stand by, or try.'},
];
export const PUBLIC_LORE={
 nhalis:{title:'Nhalis',source:'Life in the Ember Courtyard',text:'Nhalis is growing colder as its sacred lights weaken. Failed crops, lost roads, and frightened wildlife are everyday realities here.'},
 fire:{title:'The First Fire',source:'Public teaching of the Aureate Synod',text:'The Synod teaches that the First Fire brought warmth and life to the world, and that its extinction would end all existence. The courtyard’s dependence on its failing ward makes this teaching feel painfully immediate.'},
 synod:{title:'The Aureate Synod',source:'Sister Oryn',text:'The Synod tends shrines, maintains sacred records, and protects important roads. Oryn still shares the temple’s last medicines. Its members do not all respond to the crisis in the same way.'},
 ward:{title:'The silent ward',source:'Your inspection of the ruined approach',text:'The ward is cold. Red roots surround it, and fresh boot marks suggest that someone visited after the light failed. This observation does not explain the First Fire’s decline.'},
 covenant:{title:'The Ashen Covenant',source:'Signs on the shrine road',text:'Crimson cloth, altered flame marks, and a guarded road point to organized activity. The Covenant is known for forbidden rituals and attacks on sacred places. These signs alone do not explain its full purpose.'},
 inscription:{title:'The order of tending',source:'Weathered shrine inscription',text:'“First shelter the root. Then raise the ward. At last receive the ember.” A second line reads: “Where the flame gives, the earth must yield.” These appear to be old religious instructions; their meaning is uncertain.'},
 mirror:{title:'Veilglass Mirror',source:'A pilgrim’s cache in the Forsaken Shrine',text:'A small cloudy mirror reveals a concealed mark on a sealed doorway. Its maker is unknown. Pilgrims once carried objects like this to read worn sacred signs.'},
 ritual:{title:'The broken sanctuary seal',source:'Your confrontation in the inner sanctuary',text:'A Covenant ritualist was using a damaged seal to turn the guardian against the local ward. Their willingness to endanger the courtyard was real. One confrontation cannot speak for every member of the Covenant.'},
 warden:{title:'The Rootbound Warden',source:'Your battle in the Forsaken Shrine',text:'An ancient guardian bound to a local sanctuary. Corruption altered its duty. Its stone shell resisted ordinary blows, and the roots tightened when it was wounded.'},
 light:{title:'A small light restored',source:'Your return to the Ember Courtyard',text:'The local sanctuary burns again and warmth has reached the settlement. You have not rekindled the First Fire. The courtyard’s relief is real, and the larger crisis remains.'},
};
export const CHAPTER_MAPS={
 home:{name:'Your Courtyard Home',subtitle:'A mended blanket. A familiar chair. A reason to return.',blockers:[{x:32,y:32,w:896,h:144},{x:32,y:176,w:112,h:400},{x:816,y:176,w:112,h:400}],objects:[],exits:[{edge:'south',label:'Ember courtyard',destination:'courtyard',spawn:{x:176,y:256}}]},
 supply:{name:'The Courtyard Supply House',subtitle:'Whatever can be repaired still has a use.',blockers:[{x:32,y:32,w:896,h:144},{x:32,y:176,w:112,h:400},{x:816,y:176,w:112,h:400}],objects:[],exits:[{edge:'south',label:'Ember courtyard',destination:'courtyard',spawn:{x:816,y:256}}]},
 sanctuary:{name:'The Forsaken Shrine — Inner Sanctuary',subtitle:'A local sacred light, bound behind a broken seal.',blockers:[{x:32,y:32,w:192,h:576},{x:736,y:32,w:192,h:576},{x:224,y:32,w:512,h:64}],objects:[],exits:[{edge:'south',label:'Forsaken shrine',destination:'shrine',spawn:{x:480,y:176}}]},
};
export function createChapter(){return {id:1,phase:'settlement',committed:false,spoken:[],homeNote:false,cloak:false,camp:false,technique:false,puzzleClue:false,puzzle:[],puzzleSolved:false,sealOpened:false,ritualStarted:false,ritualSeen:false,lightRestored:false,completed:false,endingSeen:false,tutorialSeen:false,wayflames:[],lore:['nhalis','fire']};}
export function startChapter(world,game){world.chapter=createChapter();game.chapterEdition=true;initializeInventory(game);log(game,`${game.name} begins in the Ember Courtyard, among people worth returning to.`,'story');return world;}
export function remember(world,id){if(PUBLIC_LORE[id]&&!world.chapter.lore.includes(id))world.chapter.lore.push(id);}
export function chapterObjective(world){const c=world.chapter,f=world.flags;
 if(!c.committed){
  if(f.ward)return {phase:'settlement',title:'Return with what you know',text:'Tell the caretaker about the cold ward and the fresh marks. Choose why you will act before opening the sanctuary passage.'};
  if(f.gate)return {phase:'settlement',title:'Inspect the silent ward',text:'Examine the unlit ward beyond the raised gate. The courtyard is waiting for word.'};
  if(f.quest)return {phase:'settlement',title:'A road worth opening',text:'Take the eastern road and inspect the gate mechanism. Supplies and equipment are available in the courtyard.'};
  return {phase:'settlement',title:'A world without hope',text:'This is your home. Speak to the caretaker beside the communal fire. Explore the houses and listen to your neighbors.'};
 }

 if(c.completed)return {phase:'complete',title:'Glimmer of Hope',text:'The courtyard has felt the warmth you restored. Chapter I is complete. The First Fire still fades; your larger journey awaits.',complete:true};
 if(c.lightRestored)return {phase:'return',title:'Bring the light home',text:'Return to the caretaker in the Ember Courtyard. An awakened Wayflame can spare the walk through cleared roads.'};
 if(world.cleared.includes('shrine-warden'))return {phase:'sanctuary',title:'Preserve the local ember',text:'Examine the brazier at the north end of the inner sanctuary. The central First Fire has not been restored.'};
 if(c.ritualSeen)return {phase:'sanctuary',title:'Stand against the ritual',text:'Defeat the Rootbound Warden. Its heavy move is telegraphed; guard to endure it and use abilities against its carapace.'};
 if(c.sealOpened)return {phase:'sanctuary',title:'The first shadow',text:'Step through the northern passage into the inner sanctuary. Someone has disturbed its sacred seal.'};
 if(c.puzzleSolved&&!c.technique)return {phase:'ruins',title:'Find a way to read the seal',text:'Search the pilgrim’s cache in the southeast corner of the shrine. A worn mark conceals the door’s final lock.'};
 if(c.puzzleSolved)return {phase:'ruins',title:'Read the hidden sigil',text:'Use the Veilglass Mirror at the sealed passage north of the three mechanisms.'};
 if(world.visited.includes('shrine'))return {phase:'ruins',title:'Whispers in the ruins',text:'Read the scored inscription. The three mechanisms must be tended in the old order; the pilgrim’s cache may help with the seal.'};
 if(f.reported)return {phase:'wilderness',title:'Beyond the dying light',text:'Follow the ward road east into the Ashen Wood. Investigate the camp and the northern shrine road.'};
 if(f.ward)return {phase:'settlement',title:'Return with what you know',text:'Tell the caretaker about the cold ward and the fresh marks. You can choose how to express your resolve.'};
 if(f.gate)return {phase:'settlement',title:'Inspect the silent ward',text:'Examine the unlit ward beyond the raised approach gate. The courtyard is waiting for word.'};
 if(f.quest)return {phase:'settlement',title:'A road worth opening',text:'Take the eastern road and inspect the gate mechanism. Supplies and equipment are available in the courtyard.'};
 return {phase:'settlement',title:'A world without hope',text:'This is your home. Speak to the caretaker beside the communal fire. Explore the houses and listen to your neighbors.'};
}
export function chapterBlockers(world){return world.chapter&&world.map==='shrine'&&!world.chapter.sealOpened?[{x:224,y:112,w:512,h:16}]:[];}
export function chapterObjects(world,game){if(!world.chapter)return [];const c=world.chapter;
 const objects=[
 {id:'home-door',map:'courtyard',kind:'door',name:'Your home',x:176,y:224},
 {id:'supply-door',map:'courtyard',kind:'door',name:'Supply house',x:816,y:224},
 {id:'baker',map:'courtyard',kind:'resident',name:'The baker',sprite:0,x:544,y:432},
 {id:'tavi',map:'courtyard',kind:'resident',name:'Tavi and their mother',sprite:1,x:368,y:480},
 {id:'skeptic',map:'courtyard',kind:'resident',name:'The stoneworker',sprite:2,x:704,y:400},
 {id:'oryn',map:'courtyard',kind:'resident',name:'Sister Oryn',sprite:3,x:672,y:256},
 {id:'home-note',map:'home',kind:'stone',name:'A note beside the family picture',x:480,y:208},
 {id:'home-cloak',map:'home',kind:'chest',name:'Mended travel cloak',x:256,y:432},
 {id:'home-hearth',map:'home',kind:'fire',name:'Your hearth',x:704,y:224},
 {id:'harker',map:'supply',kind:'resident',name:'Harker',sprite:2,x:624,y:336},
 {id:'supply-ledger',map:'supply',kind:'stone',name:'The supply ledger',x:336,y:208},
 {id:'camp',map:'forest',kind:'stone',name:'Abandoned ward camp',x:592,y:416},
 {id:'ruins-cache',map:'shrine',kind:'chest',name:'Pilgrim’s cache',x:624,y:480},
 {id:'rune-root',map:'shrine',kind:'rune',name:'Root mechanism',symbol:'ROOT',x:320,y:304},
 {id:'rune-ward',map:'shrine',kind:'rune',name:'Ward mechanism',symbol:'WARD',x:480,y:352},
 {id:'rune-ember',map:'shrine',kind:'rune',name:'Ember mechanism',symbol:'EMBER',x:640,y:304},
 {id:'ruins-seal',map:'shrine',kind:'seal',name:'Sealed sanctuary passage',x:480,y:144},
 {id:'cult-voice',map:'sanctuary',kind:'cult',name:'A Covenant ritualist',x:480,y:432},
 {id:'warden-statue',map:'sanctuary',kind:'guardian',name:'The still guardian',x:480,y:304},
 {id:'sanctuary-light',map:'sanctuary',kind:'ward',name:'The local sanctuary brazier',x:480,y:160},
 ...['courtyard','forest','sanctuary'].map((map,i)=>({id:'wayflame-'+map,map,kind:'wayflame',name:'Ancient Wayflame',x:[592,864,640][i],y:[272,256,464][i]})),
 ];
 for(const id of ['knight','warrior','paladin']){const companion=COMPANIONS.find(n=>n.id===id);if(!game?.companions?.some(h=>h.id===id))objects.push({...companion,id:'counterpart-'+id,classId:id,kind:'counterpart'});}
 return objects.filter(o=>o.map===world.map&&(o.id!=='cult-voice'||!c.ritualSeen)&&(o.id!=='warden-statue'||!c.ritualSeen));
}
const say=(object,speaker,lines,lastLabel='Return',finish=null,choices=undefined)=>({id:object.id,speaker,lines,lastLabel,finish,...(choices?{choices}:{})});
export function chapterInteract(world,game,object){if(!world.chapter)return null;const c=world.chapter;
 if(object.id==='caretaker'&&c.lightRestored){if(c.completed)return say(object,'The caretaker',['They are coming out of their houses again. Not because the night has ended. Because it need not have the last word.','The First Fire still needs help. Wherever your next road takes you, this courtyard will remember why you went.']);return say(object,'The caretaker',['The ward answered before you reached the gate. Tavi ran here to tell me the stones were warm. I thought they had imagined it.','You did not save the whole world. You saved something we had stopped believing could be saved. There is a difference between waiting for a savior and seeing a neighbor choose to act.','For the first time in a long while, we have a glimmer of hope. Not a promise that all will be well. A reason to try.'],'Finish Chapter I','chapter-complete');}
 if(object.id==='caretaker'&&world.flags.ward&&!world.flags.reported)return say(object,'The caretaker',['Cold stone, fresh footprints. Then the ward did not simply go quiet without anyone noticing.','Some say the First Fire will recover if our prayers are faithful enough. Others say we should stop hoping. I can give you neither certainty nor an order.','The older shrine lies north of the Ashen Wood. It may still hold a light—and someone may be trying to prevent it. Why would you go?'],'Choose your resolve','resolve',[
 {label:'For the people who live here.',value:'people'},
 {label:'Because waiting has changed nothing.',value:'act'},
 {label:'I cannot promise success. I can try.',value:'try'},
 ]);
 if(object.id.startsWith('counterpart-')){const cls=object.classId,n=COMPANIONS.find(v=>v.id===cls),same=game.hero.id===cls;return say(object,n.name,[same?`We practice the same calling. That does not mean we must take the same road. ${n.motivation}`:n.join[0],cls==='knight'?'Someone must keep this courtyard safe while you investigate. I will hold that duty. Do not mistake staying for giving up.':cls==='warrior'?'I am looking for people, not a war. Open roads matter. If you learn anything of the hill settlements, bring word.':'I will stay with the injured for now. If a small ward can answer again, perhaps our prayers still have somewhere to go.']);}
 const responses={baker:c.lightRestored?['The dough rose this morning. Just a little. I had forgotten how impatient people become when they expect fresh bread.','Take that as thanks. I am out of speeches.']:['I measure the flour twice before I bake. It does not make more, but for a moment it feels as if I am doing something.','If the temple has an answer, I wish it would come before my neighbors start calling hunger a test of faith.'],tavi:c.lightRestored?['Tavi holds out a mitten. “The stones are warm. I checked with both hands.”','Their mother does not ask whether the world is saved. “Thank you for coming back,” she says.']:['“Will there be a summer again?” Tavi asks. Their mother folds a small, mended mitten into a pocket.','“We have enough wood for tonight,” she says. It is the answer she can give.'],skeptic:c.lightRestored?['I said stone could not remember warmth once it had gone cold. I was wrong about that.','Do not let them turn you into a story that forgets the work. We may all have more work to do.']:['A shrine is a building. I can mend a building. I cannot mend the sky.','People keep waiting for a hero. You are a neighbor with worn boots. That is not an insult. It is a warning.'],oryn:c.lightRestored?['I kept the last medicine because I thought there would be no more mornings to need it. Today I opened the cupboard.','The First Fire still fades. This light is only a beginning. But beginnings deserve care.']:['The Aureate Synod teaches that the First Fire brought warmth and life to Nhalis. Without it, we are taught, nothing will remain.','I have seen lamps fail and people sicken with the cold. I believe our light matters. I also believe a prayer is no reason to withhold the last medicine.']};
 if(responses[object.id]){if(!c.spoken.includes(object.id))c.spoken.push(object.id);if(object.id==='oryn')remember(world,'synod');return say(object,object.name,responses[object.id]);}
 switch(object.id){
 case 'home-door':case 'supply-door':return say(object,object.name,[object.id==='home-door'?'Your key still fits. The coat by the door is where you left it.':'Harker has opened the old house to anyone whose equipment can still be repaired.'],'Enter',object.id==='home-door'?'enter-home':'enter-supply');
 case 'home-note':c.homeNote=true;return say(object,'The note',['“There is a second blanket in the chest. Eat before you go. Leave the latch loose, so you need not find your key in the dark.”','The note is ordinary. That is why you fold it carefully before leaving.']);
 case 'home-cloak':if(c.cloak)return say(object,object.name,['The chest is empty. Your mended cloak is already in your inventory.']);return say(object,object.name,['Someone stitched the hem and lined the shoulders. It is not a hero’s armor. It is something made because you might be cold.'],'Take the cloak','take-cloak');
 case 'home-hearth':return say(object,'Your hearth',['The fire holds for another night. You know every chair in this room.'],'Rest','rest');
 case 'harker':return say(object,'Harker',['I can mend a weapon. I cannot make the night shorter. Bring me what you have and we will do the useful part.'],'See supplies','shop');
 case 'supply-ledger':return say(object,'Supply ledger',['Firewood: rationed. Flour: borrowed. Medicine: two bottles sent to Sister Oryn.','Beside a crossed-out debt, Harker has written: “Collect when there is a harvest.”']);
 case 'camp':c.camp=true;remember(world,'covenant');return say(object,'Abandoned ward camp',['The cookfire is cold. A bowl holds a meal left unfinished. The bedrolls were taken, but the pilgrims’ prayer strips remain.','A crimson cord binds a fresh mark around the flame symbol. This was deliberate. A northern trail leads toward the Forsaken Shrine.']);
 case 'shrine-stone':c.puzzleClue=true;remember(world,'inscription');return say(object,'Scored inscription',['“First shelter the ROOT. Then raise the WARD. At last receive the EMBER.”','The three mechanisms bear those same words. Beneath them: “Where the flame gives, the earth must yield.”','Someone has scored a newer circle across the older flame mark. Its purpose is unclear.']);
 case 'ruins-cache':if(c.technique)return say(object,object.name,['You already recovered the Veilglass Mirror. Its faint reflection can reveal the doorway’s hidden mark.']);return say(object,object.name,['A cloudy mirror rests in a pilgrim’s satchel. Held against the inscription, it reveals a line you could not see before.','You can learn Read Sigil from this relic. It uses no combat focus and works regardless of your starting class.'],'Take the mirror','take-mirror');
 case 'rune-root':case 'rune-ward':case 'rune-ember':return say(object,object.name,[c.puzzleSolved?'All three mechanisms hold their ancient positions.':`The ${object.symbol.toLowerCase()} mechanism turns with a quiet click. The inscription may tell you which should be tended first.`],c.puzzleSolved?'Return':'Turn mechanism',c.puzzleSolved?null:object.id);
 case 'ruins-seal':if(!c.committed)return say(object,object.name,['Before following this road farther, return to the courtyard caretaker with what you found at the cold ward. Decide why you choose to act.']);if(c.sealOpened)return say(object,object.name,['The passage is open. Step through the northern doorway to reach the inner sanctuary.']);if(!c.puzzleSolved)return say(object,object.name,['The stone remains fast. Three small channels lead from the mechanisms below. Their order matters.']);if(!c.technique)return say(object,object.name,['The mechanisms answer, but a worn sigil keeps the door sealed. Search the pilgrim’s cache for a way to read it.']);return say(object,object.name,['The mirror reveals a simple pilgrim’s mark hidden beneath the scored stone. You trace it with a steady hand.'],'Use Read Sigil','open-seal');
 case 'cult-voice':return ritualDialogue(object);
 case 'warden-statue':return say(object,'The still guardian',['Brass and stone, caught in the red roots. The seal at its feet has been cut open.','The figure nearer the entrance is watching you.']);
 case 'sanctuary-light':if(c.lightRestored)return say(object,'The local sanctuary light',['A small steady flame. Warmth has begun to travel back along the ward road.','The First Fire remains far beyond this place. This is a local light, and a real beginning.']);if(!world.cleared.includes('shrine-warden'))return say(object,object.name,['The ritual still binds this ward. Stop the guardian before attempting to preserve its ember.']);return say(object,object.name,['Under the ash, a coal still holds a little warmth. The broken ritual can no longer smother it.','You shelter it with both hands. No prophecy tells you what will happen. You remember the note at home, and the people waiting by the courtyard fire.'],'Preserve this light','restore-light');
 default:if(object.id.startsWith('wayflame-')){if(world.map==='sanctuary'&&!c.lightRestored)return say(object,object.name,['The sacred travel marker is cold. It may answer after the sanctuary light returns.']);if(c.wayflames.includes(world.map))return say(object,object.name,['This Wayflame remembers your arrival. It can carry you to other awakened markers.'],'Open wayflame map','waymap');return say(object,object.name,['The small marker answers your touch. Pilgrims call these Wayflames: blessings of the First Fire that remember the roads we have walked.'],'Awaken Wayflame','way-'+world.map);}
 }
 return null;
}
export function ritualDialogue(object={id:'cult-voice'}){return say(object,'A Covenant ritualist',['“You carry hope as if it were bread. As if a few more days of warmth could change what is coming.”','“The Ashen Covenant will not kneel before a dying age. We will break its sacred seals. Let what waits beyond answer us.” Red roots tighten around the guardian.','You remember the courtyard. “There are people on that road. Their lives are not an offering.”'],'Stand against the ritual','confront-ritual');}
export function chapterTrigger(world){const c=world.chapter;if(c&&world.map==='sanctuary'&&!c.ritualStarted&&world.y<=492){c.ritualStarted=true;return {...ritualDialogue(),page:0};}return null;}
export function chapterFinish(world,game,finish,choice){const c=world.chapter;if(!c)return null;
 let outcome=null;
 switch(finish){
 case 'enter-home':case 'enter-supply':world.map=finish==='enter-home'?'home':'supply';world.x=480;world.y=544;world.facing='north';if(!world.visited.includes(world.map))world.visited.push(world.map);break;
 case 'take-cloak':if(c.cloak)return false;c.cloak=true;addItem(game,'mended-cloak');outcome='Mended cloak added. Open Menu → Equipment to wear it.';break;
 case 'take-mirror':if(c.technique)return false;c.technique=true;addItem(game,'veilglass-mirror');remember(world,'mirror');outcome='Veilglass Mirror acquired · Read Sigil learned';break;
 case 'resolve':if(!world.flags.ward||!['people','act','try'].includes(choice))return false;c.committed=true;c.resolve=choice;world.flags.reported=true;world.flags.quest=true;world.flags.caretaker=true;remember(world,'ward');if(!c.wayflames.includes('courtyard'))c.wayflames.push('courtyard');log(game,choice==='people'?'You choose to go for the people who live here.':choice==='act'?'You choose to act rather than wait.':'You cannot promise success. You promise to try.','story');break;
 case 'rune-root':case 'rune-ward':case 'rune-ember':{if(c.puzzleSolved)break;const symbol=finish.slice(5),order=['root','ward','ember'];if(symbol!==order[c.puzzle.length]){c.puzzle=[];outcome='The mechanisms fall quiet. Read the inscription and try the order again.';}else{c.puzzle.push(symbol);if(c.puzzle.length===3){c.puzzleSolved=true;outcome='Root · Ward · Ember. The three channels answer.';}else outcome=`${symbol.toUpperCase()} holds · ${c.puzzle.length} / 3 aligned`;}break;}
 case 'open-seal':if(!c.committed||!c.puzzleSolved||!c.technique)return false;c.sealOpened=true;outcome='The sanctuary passage opens.';break;
 case 'confront-ritual':c.ritualStarted=true;c.ritualSeen=true;remember(world,'ritual');break;
 case 'restore-light':if(!world.cleared.includes('shrine-warden'))return false;c.lightRestored=true;world.flags.shrine=true;remember(world,'warden');remember(world,'light');for(const map of ['courtyard','sanctuary'])if(!c.wayflames.includes(map))c.wayflames.push(map);partyMembers(game).forEach(h=>{const stats=heroStats(h);h.hp=stats.hp;h.mp=stats.mp;});outcome='A small light returns. The courtyard’s ward begins to answer.';break;
 case 'chapter-complete':if(!c.committed||!c.lightRestored)return false;c.completed=true;remember(world,'light');log(game,'Chapter I — Glimmer of Hope. The courtyard has a reason to try. The First Fire still fades.','story');break;
 case 'shop':case 'waymap':break;
 default:if(finish?.startsWith('way-')){const map=finish.slice(4);if(!['courtyard','forest','sanctuary'].includes(map)||map!==world.map||map==='sanctuary'&&!c.lightRestored)return false;if(!c.wayflames.includes(map))c.wayflames.push(map);outcome='Wayflame awakened · Travel from Menu → Map';}else return null;
 }
 c.phase=chapterObjective(world).phase;return {ok:true,notice:outcome};
}
export function travelWayflame(world,game,map){if(!world.chapter||game.status!=='preparing'||world.conversation||!world.chapter.wayflames.includes(map)||map==='sanctuary'&&!world.chapter.lightRestored)return false;const point={courtyard:{x:464,y:368},forest:{x:864,y:304},sanctuary:{x:640,y:496}}[map];if(!point)return false;world.map=map;Object.assign(world,point);world.facing='south';world.grace=64;if(!world.visited.includes(map))world.visited.push(map);return true;}
export const CHAPTER_FINISHES=['enter-home','enter-supply','take-cloak','take-mirror','resolve','rune-root','rune-ward','rune-ember','open-seal','confront-ritual','restore-light','chapter-complete','shop','waymap','way-courtyard','way-forest','way-sanctuary'];
export function validChapter(world){const c=world.chapter;if(c===undefined)return true;if(!c||c.id!==1||!['settlement','wilderness','ruins','sanctuary','return','complete'].includes(c.phase)||!['committed','homeNote','cloak','camp','technique','puzzleClue','puzzleSolved','sealOpened','ritualStarted','ritualSeen','lightRestored','completed','endingSeen','tutorialSeen'].every(k=>typeof c[k]==='boolean'))return false;
 if(!Array.isArray(c.spoken)||new Set(c.spoken).size!==c.spoken.length||!c.spoken.every(id=>['baker','tavi','skeptic','oryn'].includes(id))||!Array.isArray(c.lore)||new Set(c.lore).size!==c.lore.length||!c.lore.every(id=>PUBLIC_LORE[id])||!Array.isArray(c.wayflames)||new Set(c.wayflames).size!==c.wayflames.length||!c.wayflames.every(map=>['courtyard','forest','sanctuary'].includes(map)))return false;
 if(!Array.isArray(c.puzzle)||c.puzzle.length>3||!c.puzzle.every((v,i)=>v===['root','ward','ember'][i])||c.puzzleSolved&&c.puzzle.length!==3||c.sealOpened&&(!c.committed||!c.puzzleSolved||!c.technique)||c.ritualStarted&&!c.sealOpened||c.ritualSeen&&!c.ritualStarted||world.cleared.includes('shrine-warden')&&!c.ritualSeen||c.lightRestored&&!world.cleared.includes('shrine-warden')||c.completed&&(!c.committed||!c.lightRestored)||c.endingSeen&&!c.completed||c.wayflames.includes('sanctuary')&&!c.lightRestored)return false;
 return c.committed?world.flags.reported&&['people','act','try'].includes(c.resolve):c.resolve===undefined&&!world.flags.reported;
}
