export const COMPANIONS = [
  {id:'knight',name:'Ser Aldren',title:'An oath without a kingdom',map:'courtyard',x:656,y:352,ability:'Oathbrace',personality:'Reserved, patient, quietly protective.',motivation:'He keeps watch for families displaced from the fallen border keeps.',story:'A former ward-road knight, Aldren stayed when his garrison abandoned the courtyard. He believes an oath belongs to the people it protects.',join:['I have held this courtyard since the border lamps went out. Keeping watch is useful. Finding why they went out might be more useful still.','You are going beyond the ward. I will walk with you—provided we leave a way back for the others.'],unlock:w=>w.flags.quest},
  {id:'warrior',name:'Branna',title:'The strength to return',map:'approach',x:464,y:352,ability:'Sunder',personality:'Blunt, warm-hearted, impatient with cruelty.',motivation:'She searches the ward roads for survivors from her lost hill settlement.',story:'Branna carried three neighbors out of a root-choked village. Now she searches each road for the rest, refusing to call them dead without evidence.',join:['You raised the gate. Good. I was beginning to think I would have to pull it down.','My people scattered when the roots took our homes. If your road takes us past the old settlements, my axe is yours.'],unlock:w=>w.flags.gate},
  {id:'paladin',name:'Ilyra',title:'Faith with open eyes',map:'courtyard',x:592,y:432,ability:'Kindle',personality:'Gentle, resolute, willing to question tradition.',motivation:'She hopes to protect smaller wards while learning why their light fails.',story:'Ilyra once served a crowded flame sanctuary. She now carries its remaining medicines between dying settlements, unwilling to mistake faith for certainty.',join:['You returned with the truth, even though it brought no easy comfort. That is a kindness many people forget.','I can still call a little light to the smaller wards. Let me help you reach the shrine—and learn what happened there.'],unlock:w=>w.flags.reported},
  {id:'sorcerer',name:'Orrin',title:'The scholar of absences',map:'forest',x:656,y:288,ability:'Veil Sight',personality:'Curious, dryly humorous, easily distracted by old inscriptions.',motivation:'He studies how wards once carried the sacred flame’s light.',story:'Orrin mapped the old ward network before its links began to fail. His notebooks contain observations, not an answer; he is determined to find one honestly.',join:['The pilgrim stones used to answer each other. Now I spend most of my time recording silence. It is a disappointingly repetitive subject.','You are investigating the shrine? I would like to come. Some inscriptions are easier to read when you know which veil to lift.'],unlock:w=>w.flags.ward},
  {id:'witch',name:'Mora',title:'A name the roots remember',map:'forest',x:528,y:256,ability:'Whisperroot',personality:'Wry, guarded, loyal once trusted.',motivation:'She wants to stop the cult from twisting the old names into ritual commands.',story:'Mora learned the wood’s older language from her grandmother. A cult sentinel bound her beside the shrine road when she refused to translate its stolen inscriptions.',join:['That sentinel had questions. I disliked both the questions and the chains. Thank you for removing one of those problems.','The roots listen to old names. Someone is teaching them crueler ones. I will help you find who, if you can tolerate being corrected occasionally.'],unlock:w=>w.cleared.includes('wood-sentinel')},
  {id:'gunslinger',name:'Cass Vey',title:'The letter still matters',map:'forest',x:864,y:400,ability:'Ricochet',personality:'Practical, sardonic, attentive to small details.',motivation:'Cass is tracing a caravan that vanished while carrying food and letters to isolated villages.',story:'A ward-road courier, Cass measures a journey in deliveries rather than victories. The abandoned pack belonged to the missing caravan Cass has been following.',join:['That pack belonged to a courier I knew. Keep the supplies. They are meant to get people home.','I am following the caravan’s trail. You are following the wards. They seem to lead through the same trouble. Shall we cover each other?'],unlock:w=>w.flags.forestChest},
  {id:'monk',name:'Tarin',title:'Listening through the noise',map:'shrine',x:624,y:480,ability:'Stillwater',personality:'Observant, compassionate, quietly stubborn.',motivation:'He is looking for the pilgrims who never returned to his monastery.',story:'Tarin followed a broken pilgrimage route to the shrine. He studies the guardian’s repeating movements and believes duty can outlast understanding.',join:['The guardian repeats the same motions, but its rhythm changes when the roots tighten. Listen before you strike.','My monastery sent pilgrims here. None returned. I will help you cross this place, and perhaps we can learn what happened to them.'],unlock:w=>w.cleared.includes('wood-sentinel')},
];

export function partyMembers(game){return game.hero?[game.hero,...(game.companions||[])]:[];}
export function activeParty(game){const members=partyMembers(game);return game.activeIds?game.activeIds.map(id=>members.find(h=>h.id===id)).filter(Boolean):members.slice(0,1);}
export function memberName(game,member){return member.id===game.hero.id?game.name:COMPANIONS.find(c=>c.id===member.id)?.name||member.id;}
export function hasClass(game,id){return partyMembers(game).some(h=>h.id===id);}
export function availableCompanions(world,game){return COMPANIONS.filter(c=>c.map===world.map&&!hasClass(game,c.id)&&c.unlock(world));}
export function companionObjects(world,game){return availableCompanions(world,game).map(c=>({id:`companion-${c.id}`,name:c.name,kind:'companion',classId:c.id,x:c.x,y:c.y}));}
