// Region encounters are independent of the preserved three-floor prototype.
export const REGION_ENCOUNTERS = {
 'bone-guard':{id:'bone-guard',name:'Mourning Hollows',enemy:'Ossuary Skeleton',title:'An armored remnant',sprite:'skeleton',region:'hollows',hp:175,attack:16,reward:45,xp:30,armor:.22,intent:'Bone blade',heavyIntent:'Ossuary volley',heavyEvery:3,heavyMultiplier:1.7,description:'A forgotten guard still patrols the pilgrim vault.',flavor:'Piercing techniques and armor breaks bypass its rusted mail.'},
 'veil-succubus':{id:'veil-succubus',name:'Mourning Hollows',enemy:'Veil Succubus',title:'A Covenant-bound veilspawn',sprite:'succubus',region:'hollows',hp:190,attack:15,reward:55,xp:35,drainFocus:4,intent:'Barbed lash',heavyIntent:'Violet covenant',heavyEvery:3,heavyMultiplier:1.65,description:'A dangerous summoned presence haunts the old ritual hall.',flavor:'Her heavy curse drains focus. Guard to keep it.'},
 'marsh-ogre':{id:'marsh-ogre',name:'Greyfen March',enemy:'Peatland Ogre',title:'A brute driven from its hollow',sprite:'ogre',region:'greyfen',hp:245,attack:20,reward:65,xp:40,intent:'Club sweep',heavyIntent:'Boulder crush',heavyEvery:3,heavyMultiplier:1.85,description:'A hungry brute follows the refugee wagons.',flavor:'An overhead crush reaches every living ally.' ,sweep:true},
 'hollow-undead':{id:'hollow-undead',name:'Greyfen March',enemy:'Hollowed Pilgrim',title:'A wanderer with no road home',sprite:'undead',region:'greyfen',hp:185,attack:15,reward:45,xp:30,regen:9,intent:'Grave grasp',heavyIntent:'Gravewake',heavyEvery:3,heavyMultiplier:1.65,description:'A hollowed pilgrim shambles through the reeds.',flavor:'It regenerates unless burning. Time an incendiary technique.'},
 'beacon-vampire':{id:'beacon-vampire',name:'Beacon of Thorns',enemy:'Duskbound Vampire',title:'A predator among the ruined vows',sprite:'vampire',region:'beacon',hp:210,attack:18,reward:65,xp:40,lifeSteal:.4,intent:'Crimson rapier',heavyIntent:'Sanguine siphon',heavyEvery:3,heavyMultiplier:1.6,description:'A blood-starved noble has claimed the abandoned outer court.',flavor:'Its heavy siphon heals from actual damage. Guard to deny it.'},
 'fen-stalker':{id:'fen-stalker',name:'Greyfen March',enemy:'Fen Stalker',title:'Withered marsh hunter',sprite:'wolf',region:'greyfen',hp:150,attack:15,reward:40,xp:35,intent:'Mire bite',heavyIntent:'Reed ambush',heavyEvery:3,heavyMultiplier:1.6,description:'A withered hunter prowls the dry causeway.',flavor:'The reeds fall silent.'},
 'marsh-fanatic':{id:'marsh-fanatic',name:'Greyfen March',enemy:'Covenant Mirekeeper',title:'Extremist of the flooded road',sprite:'sentinel',region:'greyfen',hp:190,attack:16,reward:55,xp:45,intent:'Hooked blade',heavyIntent:'Ashen rite',heavyEvery:3,heavyMultiplier:1.65,description:'A fanatic guards the old tending records.',flavor:'The road has another keeper.'},
 'thorn-sentinel':{id:'thorn-sentinel',name:'Beacon of Thorns',enemy:'Thornbound Sentinel',title:'Guardian of the beacon',sprite:'warden',region:'beacon',hp:330,attack:19,reward:150,xp:100,intent:'Thorn lance',heavyIntent:'Thornstorm',heavyEvery:3,heavyMultiplier:1.7,boss:true,thornShell:true,description:'The beacon guardian refuses those who would tend its flame.',flavor:'Coordinate abilities to break its thorn shell.'},
  'ash-wolf': {id:'ash-wolf',name:'The Ashen Wood',enemy:'Ash Wolf',title:'Corrupted woodland hunter',sprite:'wolf',region:'forest',hp:90,attack:10,reward:30,xp:25,intent:'Raking bite',heavyIntent:'Feral pounce',heavyEvery:3,heavyMultiplier:1.5,description:'A wolf steps out of the mist. Red roots move beneath its fur.',flavor:'The forest is listening.'},
  'cult-sentinel': {id:'cult-sentinel',name:'The Ashen Wood',enemy:'Cult Sentinel',title:'A watcher of the dark road',sprite:'sentinel',region:'forest',hp:135,attack:13,reward:55,xp:40,intent:'Ritual blade',heavyIntent:'Bloodletting rite',heavyEvery:3,heavyMultiplier:1.6,description:'A figure in crimson bars your way. The blade is already drawn.',flavor:'Someone has been keeping this road.'},
  'root-warden': {id:'root-warden',name:'The Forsaken Shrine',enemy:'Rootbound Warden',title:'Guardian of a forgotten ward',sprite:'warden',region:'shrine',hp:240,attack:15,reward:130,xp:90,intent:'Stone fist',heavyIntent:'Rootquake',heavyEvery:3,heavyMultiplier:1.65,boss:true,description:'Stone grinds against old brass. The shrine guardian wakes.',flavor:'A local ward. An older mystery.'},
};
