import { SECOND_LORE } from './chapter-two.js';
import { memberAppearance } from './sprites.js';
import { CLASSES, heroStats } from './engine.js';
import { COMPANIONS, partyMembers, memberName } from './companions.js';
import { ITEMS, inventoryContent } from './inventory.js';
import { MAPS } from './world.js';
import { PUBLIC_LORE, chapterObjective } from './chapter.js';
import { partyContent } from './party-view.js';
import { journalContent } from './world-view.js';
export const MENU_TABS=['party','character','equipment','relics','inventory','abilities','journal','lore','map','system'];
const title={party:'Party',character:'Character',equipment:'Equipment',relics:'Relics',inventory:'Inventory',abilities:'Abilities',journal:'Journal',lore:'Lore Codex',map:'Map',system:'System'};
export function pauseContent(tab,game,world,esc,selected=game.hero.id){
 const members=partyMembers(game),member=members.find(h=>h.id===selected)||game.hero,stats=heroStats(member),identity=COMPANIONS.find(c=>c.id===member.id);
 const select=`<div class="member-selector">${members.map(h=>`<button data-action="inspect-member" data-member="${h.id}" class="${h===member?'selected':''}">${esc(memberName(game,h))}</button>`).join('')}</div>`;
 let content;
 switch(tab){
 case 'party':content=partyContent(game,esc);break;
 case 'equipment':case 'inventory':content=inventoryContent(game,esc);break;
 case 'character':content=`<h2 id="dialog-title">${esc(memberName(game,member))}</h2>${select}<div class="character-dialog"><div class="frame-sprite ${memberAppearance(game,member).className}" data-gender="${memberAppearance(game,member).gender}" data-rows="${memberAppearance(game,member).rows}"></div><div><h3>Level ${member.level} ${stats.name}</h3><p>${hIdentity(game,member,identity,stats,esc)}</p><p>${member.hp} / ${stats.hp} health · ${member.mp} / ${stats.mp} focus</p><p>${stats.attack} attack · ${stats.defense} armor · ${stats.focusRecovery} focus restored per enemy phase</p><p>${game.xp} shared experience. Reserves gain the same level as the active party.</p></div></div>`;break;
 case 'abilities':content=`<h2 id="dialog-title">Practiced and discovered</h2>${select}<article class="menu-entry"><h3>${stats.skill}</h3><p>${stats.description}</p><p>${stats.cost} focus · Select Ability during this character’s combat turn.</p></article><article class="menu-entry"><h3>${identity.ability}</h3><p>Approach a matching environmental object and choose to use this class ability. Recruited reserves contribute their exploration abilities.</p><p>No combat focus cost. Your protagonist’s calling remains fixed.</p></article>${world.chapter?.technique?'<article class="menu-entry"><h3>Read Sigil</h3><p>The Veilglass Mirror reveals the sealed shrine passage. Use it at the doorway after aligning Root, Ward, and Ember. Available to every starting class, without spending focus.</p></article>':''}`;break;
 case 'relics':content=`<h2 id="dialog-title">Objects that remember</h2>${(game.inventory||[]).filter(id=>ITEMS[id].slot==='charm').map(id=>`<article class="menu-entry"><h3>${ITEMS[id].name}</h3><p>${ITEMS[id].description}</p><p>${id==='veilglass-mirror'?PUBLIC_LORE.mirror.text:id==='thorn-signet'?'Recovered after tending the Beacon of Thorns. An old mark of a ruler who defended the causeways.':'Recovered from the Rootbound Warden’s sanctuary. Its warmth is faint, but persists.'}</p><button data-action="menu-tab" data-tab="equipment">Manage equipment</button></article>`).join('')||'<p>No relics discovered yet. Investigate the pilgrim’s cache in the Forsaken Shrine.</p>'}`;break;
 case 'journal':content=journalContent(world,game);if(world.chapterTwo)content+=`<ol class="quest-checklist">${[['Accept Lornwatch’s petition',world.chapterTwo.requested],['Brace the crossing',world.chapterTwo.brace],['Read the pilgrim ledger',world.chapterTwo.record],['Kindle the sanctuary cup',world.chapterTwo.kindled],['Choose the tending rite',Boolean(world.chapterTwo.decision)],['Overcome the Thornbound Sentinel',world.cleared.includes('thorn-sentinel')],['Restore the beacon',world.chapterTwo.restored],['Return to Lornwatch',world.chapterTwo.completed],['Deliver the blankets (optional)',world.chapterTwo.delivered]].map(([name,done])=>`<li class="${done?'done':''}">${done?'✓':'○'} ${name}</li>`).join('')}</ol><p>Chosen rite: ${world.chapterTwo.decision||'Undecided'}. Camp conversations: ${world.chapterTwo.camp?'Remembered':'Not yet shared'}.</p>`;if(world.chapter)content+=`<ol class="quest-checklist">${[['Choose to act',world.chapter.committed],['Investigate the camp',world.chapter.camp],['Align the shrine mechanisms',world.chapter.puzzleSolved],['Read the sealed passage',world.chapter.sealOpened],['Stop the ritual and guardian',world.cleared.includes('shrine-warden')],['Restore the local ember',world.chapter.lightRestored],['Return to your neighbors',world.chapter.completed]].map(([name,done])=>`<li class="${done?'done':''}">${done?'✓':'○'} ${name}</li>`).join('')}</ol>`;break;
 case 'lore':content=`<h2 id="dialog-title">What you have learned</h2><p>Accounts retain their sources. A teaching or observation is not a complete explanation.</p>${(world.chapter?.lore||['nhalis','fire']).map(id=>`<article class="menu-entry"><small>${esc(PUBLIC_LORE[id].source)}</small><h3>${PUBLIC_LORE[id].title}</h3><p>${PUBLIC_LORE[id].text}</p></article>`).join('')}${(world.chapterTwo?.lore||[]).map(id=>`<article class="menu-entry"><small>${esc(SECOND_LORE[id].source)}</small><h3>${SECOND_LORE[id].title}</h3><p>${SECOND_LORE[id].text}</p></article>`).join('')}`;break;
 case 'map':content=`<h2 id="dialog-title">The ward roads</h2><p>Courtyard ⇄ Ruined Approach ⇄ Ashen Wood ⇄ Forsaken Shrine ⇄ Inner Sanctuary. Your home and supply house open onto the courtyard. After Chapter I, Ashen Wood connects to Lornwatch and Greyfen March. Greyfen’s north road reaches the Beacon of Thorns; its south road reaches the Mourning Hollows.</p><div class="region-map">${Object.entries(MAPS).filter(([id])=>world.chapterTwo||!['lornwatch','greyfen','hollows','beacon'].includes(id)).map(([id,m])=>`<article class="${world.visited.includes(id)?'discovered':''}"><small>${world.map===id?'YOU ARE HERE':world.visited.includes(id)?'DISCOVERED':'UNEXPLORED'}</small><h3>${esc(m.name)}</h3>${world.chapter?.wayflames.includes(id)?`<button data-action="way-travel" data-map="${id}" ${game.status!=='preparing'||world.conversation||world.map===id?'disabled':''}>Travel to Wayflame</button>`:'<span>No awakened Wayflame</span>'}</article>`).join('')}</div><p>${world.chapter?chapterObjective(world).text:'Follow the roads to discover the region.'}</p>`;break;
 case 'system':content=`<h2 id="dialog-title">Keep your journey</h2><p>Autosave preserves your world, class, equipment, quests, discoveries, and battle commands.</p><div class="system-actions"><button data-action="save-now">Save now</button><button data-action="load-now">Load saved journey</button><button data-action="export-save">Download save file</button><label class="save-import">Import save file<input id="save-import" type="file" accept="application/json,.json"></label><button data-action="sound">Toggle music and sound</button><button data-action="close">Return to game</button><button data-action="restart">New adventure</button></div><p>WASD / arrows: move · Shift: run · E / Enter: interact · P / Escape: menu · 1–4: combat commands · R: retreat. Touch controls are available below the world. Enable reduced motion in your device’s accessibility settings to shorten effects.</p><p id="system-status" role="status"></p>`;break;
 default:content='<h2 id="dialog-title">Your journey</h2>';
 }
 return `<nav class="pause-tabs" aria-label="RPG management">${MENU_TABS.map(id=>`<button data-action="menu-tab" data-tab="${id}" class="${tab===id?'selected':''}">${title[id]}</button>`).join('')}</nav><div class="pause-content">${content}</div>`;
}
function hIdentity(game,member,identity,stats,esc){return esc(member===game.hero?'A resident of the Ember Courtyard. Your class is fixed for this journey.':identity.story);}
export function shopContent(game){const id=`tempered-${game.hero.id}`;return `<div class="eyebrow">HARKER’S REPAIRS & SUPPLIES</div><h2 id="dialog-title">Do the useful part.</h2><p>${game.gold} gold · ${game.potions} potions. Equipment can be worn through the Equipment menu.</p><div class="inventory-grid">${[[id,20],['mended-cloak',20],['potion',15]].map(([item,price])=>`<article><h3>${item==='potion'?'Healing potion':ITEMS[item].name}</h3><p>${item==='potion'?'Restores up to 50 health during combat.':ITEMS[item].description}</p><button data-action="buy" data-item="${item}" ${game.status!=='preparing'||game.gold<price||game.inventory?.includes(item)?'disabled':''}>${game.inventory?.includes(item)?'Already owned':`Buy · ${price} gold`}</button></article>`).join('')}</div>`;}
